/*******************************************************/
/**  Autogenerated list structure for cart_in_out/it_dur_stats.c    */
/*******************************************************/

#include "cst_synth.h"


static const dur_stat dur_stat_pau = { "#", 0.3, 0.18 };
static const dur_stat dur_stat_dz = { "dz", 0.068636, 0.029203 };
static const dur_stat dur_stat_nf = { "nf", 0.057007, 0.028997 };
static const dur_stat dur_stat_J = { "J", 0.073194, 0.023017 };
static const dur_stat dur_stat_S = { "S", 0.094839, 0.036893 };
static const dur_stat dur_stat_dZ = { "dZ", 0.092576, 0.029872 };
static const dur_stat dur_stat_ng = { "ng", 0.0983, 0.044676 };
static const dur_stat dur_stat_L = { "L", 0.071333, 0.028949 };
static const dur_stat dur_stat_v = { "v", 0.066575, 0.021357 };
static const dur_stat dur_stat_u1 = { "u1", 0.117841, 0.10523 };
static const dur_stat dur_stat_e1 = { "e1", 0.089335, 0.06004 };
static const dur_stat dur_stat_g = { "g", 0.082426, 0.028684 };
static const dur_stat dur_stat_z = { "z", 0.10332, 0.019146 };
static const dur_stat dur_stat_j = { "j", 0.077196, 0.033514 };
static const dur_stat dur_stat_tS = { "tS", 0.103878, 0.025793 };
static const dur_stat dur_stat_o1 = { "o1", 0.112878, 0.058883 };
static const dur_stat dur_stat_p = { "p", 0.089808, 0.031395 };
static const dur_stat dur_stat_a = { "a", 0.06891, 0.043689 };
static const dur_stat dur_stat_f = { "f", 0.098453, 0.034646 };
static const dur_stat dur_stat_E1 = { "E1", 0.114734, 0.053936 };
static const dur_stat dur_stat_s = { "s", 0.114217, 0.04546 };
static const dur_stat dur_stat_w = { "w", 0.074278, 0.034692 };
static const dur_stat dur_stat_i = { "i", 0.075528, 0.04418 };
static const dur_stat dur_stat_t = { "t", 0.085058, 0.038368 };
static const dur_stat dur_stat_a1 = { "a1", 0.117478, 0.06397 };
static const dur_stat dur_stat_ts = { "ts", 0.081637, 0.037346 };
static const dur_stat dur_stat_u = { "u", 0.079503, 0.042826 };
static const dur_stat dur_stat_n = { "n", 0.07725, 0.043168 };
static const dur_stat dur_stat_d = { "d", 0.085933, 0.034872 };
static const dur_stat dur_stat_e = { "e", 0.071421, 0.042662 };
static const dur_stat dur_stat_r = { "r", 0.062013, 0.026931 };
static const dur_stat dur_stat_b = { "b", 0.086976, 0.028861 };
static const dur_stat dur_stat_m = { "m", 0.093536, 0.038037 };
static const dur_stat dur_stat_O1 = { "O1", 0.126967, 0.090979 };
static const dur_stat dur_stat_o = { "o", 0.079483, 0.052808 };
static const dur_stat dur_stat_k = { "k", 0.088872, 0.030368 };
static const dur_stat dur_stat_l = { "l", 0.079695, 0.031066 };
static const dur_stat dur_stat_i1 = { "i1", 0.09337, 0.058105 };


const dur_stat * const it_dur_stats[] = {
&dur_stat_pau,
&dur_stat_dz,
&dur_stat_nf,
&dur_stat_J,
&dur_stat_S,
&dur_stat_dZ,
&dur_stat_ng,
&dur_stat_L,
&dur_stat_v,
&dur_stat_u1,
&dur_stat_e1,
&dur_stat_g,
&dur_stat_z,
&dur_stat_j,
&dur_stat_tS,
&dur_stat_o1,
&dur_stat_p,
&dur_stat_a,
&dur_stat_f,
&dur_stat_E1,
&dur_stat_s,
&dur_stat_w,
&dur_stat_i,
&dur_stat_t,
&dur_stat_a1,
&dur_stat_ts,
&dur_stat_u,
&dur_stat_n,
&dur_stat_d,
&dur_stat_e,
&dur_stat_r,
&dur_stat_b,
&dur_stat_m,
&dur_stat_O1,
&dur_stat_o,
&dur_stat_k,
&dur_stat_l,
&dur_stat_i1,
} ;
