/*******************************************************/
/**  Autogenerated cart trees for it_durz    */
/*******************************************************/

#include "cst_string.h"
#include "cst_cart.h"
#include "cst_regex.h"
#include "it_durz_cart.h"


static const cst_cart_node it_durz_cart_nodes[] = {
{ 0, CST_CART_OP_IS, CTNODE_it_durz_NO_0000, (cst_val *)&val_0000},
{ 1, CST_CART_OP_IS, CTNODE_it_durz_NO_0001, (cst_val *)&val_0001},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0002 },
{ 1, CST_CART_OP_IS, CTNODE_it_durz_NO_0003, (cst_val *)&val_0003},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0004 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0005 },
{ 2, CST_CART_OP_IN, CTNODE_it_durz_NO_0006, (cst_val *)&val_0006},
{ 3, CST_CART_OP_IN, CTNODE_it_durz_NO_0007, (cst_val *)&val_0007},
{ 4, CST_CART_OP_IS, CTNODE_it_durz_NO_0008, (cst_val *)&val_0008},
{ 2, CST_CART_OP_IN, CTNODE_it_durz_NO_0009, (cst_val *)&val_0009},
{ 0, CST_CART_OP_IN, CTNODE_it_durz_NO_0010, (cst_val *)&val_0010},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0011 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0012 },
{ 5, CST_CART_OP_IS, CTNODE_it_durz_NO_0013, (cst_val *)&val_0013},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0014 },
{ 6, CST_CART_OP_LESS, CTNODE_it_durz_NO_0015, (cst_val *)&val_0015},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0016 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0017 },
{ 7, CST_CART_OP_IN, CTNODE_it_durz_NO_0018, (cst_val *)&val_0018},
{ 3, CST_CART_OP_IN, CTNODE_it_durz_NO_0019, (cst_val *)&val_0019},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0020 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0021 },
{ 3, CST_CART_OP_IN, CTNODE_it_durz_NO_0022, (cst_val *)&val_0022},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0023 },
{ 2, CST_CART_OP_IN, CTNODE_it_durz_NO_0024, (cst_val *)&val_0024},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0025 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0026 },
{ 0, CST_CART_OP_IN, CTNODE_it_durz_NO_0027, (cst_val *)&val_0027},
{ 2, CST_CART_OP_IN, CTNODE_it_durz_NO_0028, (cst_val *)&val_0028},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0029 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0030 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0031 },
{ 8, CST_CART_OP_IN, CTNODE_it_durz_NO_0032, (cst_val *)&val_0032},
{ 9, CST_CART_OP_IN, CTNODE_it_durz_NO_0033, (cst_val *)&val_0033},
{ 10, CST_CART_OP_LESS, CTNODE_it_durz_NO_0034, (cst_val *)&val_0034},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0035 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0036 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0037 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0038 },
{ 255, CST_CART_OP_NONE, 0, 0}};



static const char * const it_durz_feat_table[] = {
"name",
"p.R:SylStructure.parent.parent.pbreak",
"n.name",
"p.name",
"R:SylStructure.parent.Accent_boundary_syl",
"R:SylStructure.parent.parent.R:Phrase.parent.type",
"R:SylStructure.parent.parent.R:Phrase.parent.phrasepos_in_utt",
"R:SylStructure.parent.parent.R:Word.Simbolic_word_end_punct",
"R:SylStructure.parent.parent.tPOS",
"R:SylStructure.parent.parent.p.tPOS",
"R:SylStructure.parent.syl_in",
NULL };

const cst_cart it_durz_cart = {
  it_durz_cart_nodes,
  it_durz_feat_table
};
