/*******************************************************/
/**  Autogenerated list structure for cart_in_out/it_dur_ds_stats.c    */
/*******************************************************/

#include "cst_synth.h"


static const dur_stat dur_stat_pau = { "#", 0.2, 0.1 };
static const dur_stat dur_stat_dz = { "dz", 0.07404, 0.04761 };
static const dur_stat dur_stat_S = { "S", 0.080323, 0.03403 };
static const dur_stat dur_stat_ng = { "ng", 0.07205, 0.031054 };
static const dur_stat dur_stat_nf = { "nf", 0.048434, 0.02506 };
static const dur_stat dur_stat_w = { "w", 0.03922, 0.02 };
static const dur_stat dur_stat_E = { "E", 0.045, 0.021213 };
static const dur_stat dur_stat_L = { "L", 0.04298, 0.02401 };
static const dur_stat dur_stat_g = { "g", 0.066439, 0.024859 };
static const dur_stat dur_stat_v = { "v", 0.054885, 0.026364 };
static const dur_stat dur_stat_O1 = { "O1", 0.10101, 0.054134 };
static const dur_stat dur_stat_k = { "k", 0.08709, 0.056072 };
static const dur_stat dur_stat_J = { "J", 0.045732, 0.018017 };
static const dur_stat dur_stat_o1 = { "o1", 0.080577, 0.049468 };
static const dur_stat dur_stat_z = { "z", 0.074247, 0.025445 };
static const dur_stat dur_stat_b = { "b", 0.066214, 0.02968 };
static const dur_stat dur_stat_j = { "j", 0.053492, 0.027873 };
static const dur_stat dur_stat_u1 = { "u1", 0.086907, 0.049386 };
static const dur_stat dur_stat_r = { "r", 0.042248, 0.020536 };
static const dur_stat dur_stat_s = { "s", 0.081014, 0.036614 };
static const dur_stat dur_stat_dZ = { "dZ", 0.092363, 0.044758 };
static const dur_stat dur_stat_ts = { "ts", 0.073993, 0.055017 };
static const dur_stat dur_stat_e1 = { "e1", 0.065428, 0.048684 };
static const dur_stat dur_stat_i1 = { "i1", 0.068941, 0.04246 };
static const dur_stat dur_stat_o = { "o", 0.067393, 0.038769 };
static const dur_stat dur_stat_t = { "t", 0.080033, 0.05553 };
static const dur_stat dur_stat_u = { "u", 0.060831, 0.026313 };
static const dur_stat dur_stat_a = { "a", 0.063865, 0.039864 };
static const dur_stat dur_stat_l = { "l", 0.043933, 0.024519 };
static const dur_stat dur_stat_e = { "e", 0.062816, 0.041234 };
static const dur_stat dur_stat_n = { "n", 0.053279, 0.027476 };
static const dur_stat dur_stat_E1 = { "E1", 0.083415, 0.044626 };
static const dur_stat dur_stat_f = { "f", 0.087695, 0.042924 };
static const dur_stat dur_stat_d = { "d", 0.069142, 0.03962 };
static const dur_stat dur_stat_i = { "i", 0.060185, 0.03338 };
static const dur_stat dur_stat_p = { "p", 0.0783, 0.040803 };
static const dur_stat dur_stat_m = { "m", 0.054346, 0.024986 };
static const dur_stat dur_stat_a1 = { "a1", 0.1025, 0.061986 };
static const dur_stat dur_stat_tS = { "tS", 0.101225, 0.049675 };
static const dur_stat dur_stat_O = { "O", 0.045, 0.021213 };
static const dur_stat dur_stat_Z = { "Z", 0.080323, 0.03403 };


const dur_stat * const it_dur_stats[] = {
&dur_stat_pau,
&dur_stat_dz,
&dur_stat_S,
&dur_stat_ng,
&dur_stat_nf,
&dur_stat_w,
&dur_stat_E,
&dur_stat_L,
&dur_stat_g,
&dur_stat_v,
&dur_stat_O1,
&dur_stat_k,
&dur_stat_J,
&dur_stat_o1,
&dur_stat_z,
&dur_stat_b,
&dur_stat_j,
&dur_stat_u1,
&dur_stat_r,
&dur_stat_s,
&dur_stat_dZ,
&dur_stat_ts,
&dur_stat_e1,
&dur_stat_i1,
&dur_stat_o,
&dur_stat_t,
&dur_stat_u,
&dur_stat_a,
&dur_stat_l,
&dur_stat_e,
&dur_stat_n,
&dur_stat_E1,
&dur_stat_f,
&dur_stat_d,
&dur_stat_i,
&dur_stat_p,
&dur_stat_m,
&dur_stat_a1,
&dur_stat_tS,
&dur_stat_O,
&dur_stat_Z,
} ;
