/*******************************************************/
/**  Autogenerated list structure for it_gpos    */
/*******************************************************/

#include "cst_val.h"


DEF_STATIC_CONST_VAL_STRING(art_def_0001,"art_def");
DEF_STATIC_CONST_VAL_STRING(art_def_0002,"il");
DEF_STATIC_CONST_VAL_STRING(art_def_0003,"lo");
DEF_STATIC_CONST_VAL_STRING(art_def_0004,"la");
DEF_STATIC_CONST_VAL_STRING(art_def_0005,"i");
DEF_STATIC_CONST_VAL_STRING(art_def_0006,"gli");
DEF_STATIC_CONST_VAL_STRING(art_def_0007,"le");
DEF_STATIC_CONST_VAL_STRING(art_def_0008,"l'");

static const cst_val * const gpos_art_def_list[] = {
	(cst_val *)&art_def_0001,
	(cst_val *)&art_def_0002,
	(cst_val *)&art_def_0003,
	(cst_val *)&art_def_0004,
	(cst_val *)&art_def_0005,
	(cst_val *)&art_def_0006,
	(cst_val *)&art_def_0007,
	(cst_val *)&art_def_0008,
	0 };


DEF_STATIC_CONST_VAL_STRING(art_indef_0001,"art_indef");
DEF_STATIC_CONST_VAL_STRING(art_indef_0002,"un");
DEF_STATIC_CONST_VAL_STRING(art_indef_0003,"uno");
DEF_STATIC_CONST_VAL_STRING(art_indef_0004,"una");
DEF_STATIC_CONST_VAL_STRING(art_indef_0005,"un'");

static const cst_val * const gpos_art_indef_list[] = {
	(cst_val *)&art_indef_0001,
	(cst_val *)&art_indef_0002,
	(cst_val *)&art_indef_0003,
	(cst_val *)&art_indef_0004,
	(cst_val *)&art_indef_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(pre_pro_0001,"pre_pro");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0002,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0003,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0004,"da");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0005,"in");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0006,"con");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0007,"su");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0008,"per");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0009,"tra");
DEF_STATIC_CONST_VAL_STRING(pre_pro_0010,"fra");

static const cst_val * const gpos_pre_pro_list[] = {
	(cst_val *)&pre_pro_0001,
	(cst_val *)&pre_pro_0002,
	(cst_val *)&pre_pro_0003,
	(cst_val *)&pre_pro_0004,
	(cst_val *)&pre_pro_0005,
	(cst_val *)&pre_pro_0006,
	(cst_val *)&pre_pro_0007,
	(cst_val *)&pre_pro_0008,
	(cst_val *)&pre_pro_0009,
	(cst_val *)&pre_pro_0010,
	0 };


DEF_STATIC_CONST_VAL_STRING(pre_con_0001,"pre_con");
DEF_STATIC_CONST_VAL_STRING(pre_con_0002,"al");
DEF_STATIC_CONST_VAL_STRING(pre_con_0003,"allo");
DEF_STATIC_CONST_VAL_STRING(pre_con_0004,"alla");
DEF_STATIC_CONST_VAL_STRING(pre_con_0005,"ai");
DEF_STATIC_CONST_VAL_STRING(pre_con_0006,"agli");
DEF_STATIC_CONST_VAL_STRING(pre_con_0007,"alle");
DEF_STATIC_CONST_VAL_STRING(pre_con_0008,"all'");
DEF_STATIC_CONST_VAL_STRING(pre_con_0009,"dal");
DEF_STATIC_CONST_VAL_STRING(pre_con_0010,"dallo");
DEF_STATIC_CONST_VAL_STRING(pre_con_0011,"dalla");
DEF_STATIC_CONST_VAL_STRING(pre_con_0012,"dai");
DEF_STATIC_CONST_VAL_STRING(pre_con_0013,"dagli");
DEF_STATIC_CONST_VAL_STRING(pre_con_0014,"dalle");
DEF_STATIC_CONST_VAL_STRING(pre_con_0015,"dall'");
DEF_STATIC_CONST_VAL_STRING(pre_con_0016,"del");
DEF_STATIC_CONST_VAL_STRING(pre_con_0017,"dello");
DEF_STATIC_CONST_VAL_STRING(pre_con_0018,"della");
DEF_STATIC_CONST_VAL_STRING(pre_con_0019,"dei");
DEF_STATIC_CONST_VAL_STRING(pre_con_0020,"degli");
DEF_STATIC_CONST_VAL_STRING(pre_con_0021,"delle");
DEF_STATIC_CONST_VAL_STRING(pre_con_0022,"dell'");
DEF_STATIC_CONST_VAL_STRING(pre_con_0023,"nel");
DEF_STATIC_CONST_VAL_STRING(pre_con_0024,"nello");
DEF_STATIC_CONST_VAL_STRING(pre_con_0025,"nella");
DEF_STATIC_CONST_VAL_STRING(pre_con_0026,"nei");
DEF_STATIC_CONST_VAL_STRING(pre_con_0027,"negli");
DEF_STATIC_CONST_VAL_STRING(pre_con_0028,"nelle");
DEF_STATIC_CONST_VAL_STRING(pre_con_0029,"nell'");
DEF_STATIC_CONST_VAL_STRING(pre_con_0030,"sul");
DEF_STATIC_CONST_VAL_STRING(pre_con_0031,"sullo");
DEF_STATIC_CONST_VAL_STRING(pre_con_0032,"sulla");
DEF_STATIC_CONST_VAL_STRING(pre_con_0033,"sui");
DEF_STATIC_CONST_VAL_STRING(pre_con_0034,"sugli");
DEF_STATIC_CONST_VAL_STRING(pre_con_0035,"sulle");
DEF_STATIC_CONST_VAL_STRING(pre_con_0036,"sull'");

static const cst_val * const gpos_pre_con_list[] = {
	(cst_val *)&pre_con_0001,
	(cst_val *)&pre_con_0002,
	(cst_val *)&pre_con_0003,
	(cst_val *)&pre_con_0004,
	(cst_val *)&pre_con_0005,
	(cst_val *)&pre_con_0006,
	(cst_val *)&pre_con_0007,
	(cst_val *)&pre_con_0008,
	(cst_val *)&pre_con_0009,
	(cst_val *)&pre_con_0010,
	(cst_val *)&pre_con_0011,
	(cst_val *)&pre_con_0012,
	(cst_val *)&pre_con_0013,
	(cst_val *)&pre_con_0014,
	(cst_val *)&pre_con_0015,
	(cst_val *)&pre_con_0016,
	(cst_val *)&pre_con_0017,
	(cst_val *)&pre_con_0018,
	(cst_val *)&pre_con_0019,
	(cst_val *)&pre_con_0020,
	(cst_val *)&pre_con_0021,
	(cst_val *)&pre_con_0022,
	(cst_val *)&pre_con_0023,
	(cst_val *)&pre_con_0024,
	(cst_val *)&pre_con_0025,
	(cst_val *)&pre_con_0026,
	(cst_val *)&pre_con_0027,
	(cst_val *)&pre_con_0028,
	(cst_val *)&pre_con_0029,
	(cst_val *)&pre_con_0030,
	(cst_val *)&pre_con_0031,
	(cst_val *)&pre_con_0032,
	(cst_val *)&pre_con_0033,
	(cst_val *)&pre_con_0034,
	(cst_val *)&pre_con_0035,
	(cst_val *)&pre_con_0036,
	0 };


DEF_STATIC_CONST_VAL_STRING(pre_imp_0001,"pre_imp");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0002,"contro");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0003,"presso");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0004,"sopra");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0005,"sotto");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0006,"dietro");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0007,"dentro");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0008,"dopo");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0009,"lungo");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0010,"salvo");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0011,"secondo");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0012,"durante");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0013,"mediante");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0014,"stante");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0015,"nonostante");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0016,"dato");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0017,"eccetto");
DEF_STATIC_CONST_VAL_STRING(pre_imp_0018,"tolto");

static const cst_val * const gpos_pre_imp_list[] = {
	(cst_val *)&pre_imp_0001,
	(cst_val *)&pre_imp_0002,
	(cst_val *)&pre_imp_0003,
	(cst_val *)&pre_imp_0004,
	(cst_val *)&pre_imp_0005,
	(cst_val *)&pre_imp_0006,
	(cst_val *)&pre_imp_0007,
	(cst_val *)&pre_imp_0008,
	(cst_val *)&pre_imp_0009,
	(cst_val *)&pre_imp_0010,
	(cst_val *)&pre_imp_0011,
	(cst_val *)&pre_imp_0012,
	(cst_val *)&pre_imp_0013,
	(cst_val *)&pre_imp_0014,
	(cst_val *)&pre_imp_0015,
	(cst_val *)&pre_imp_0016,
	(cst_val *)&pre_imp_0017,
	(cst_val *)&pre_imp_0018,
	0 };


DEF_STATIC_CONST_VAL_STRING(pre_pp_0001,"pre_pp");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0002,"prima");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0003,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0004,"davanti");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0005,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0006,"fino");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0007,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0008,"per");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0009,"mezzo");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0010,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0011,"la");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0012,"dà");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0013,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0014,"qua");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0015,"da");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0016,"incontro");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0017,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0018,"in");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0019,"qualità");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0020,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0021,"senza");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0022,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0023,"riguardo");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0024,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0025,"fine");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0026,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0027,"in");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0028,"mezzo");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0029,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0030,"rispetto");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0031,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0032,"insieme");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0033,"con");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0034,"accanto");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0035,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0036,"in");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0037,"quanto");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0038,"a");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0039,"invece");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0040,"di");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0041,"in");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0042,"luogo");
DEF_STATIC_CONST_VAL_STRING(pre_pp_0043,"di");

static const cst_val * const gpos_pre_pp_list[] = {
	(cst_val *)&pre_pp_0001,
	(cst_val *)&pre_pp_0002,
	(cst_val *)&pre_pp_0003,
	(cst_val *)&pre_pp_0004,
	(cst_val *)&pre_pp_0005,
	(cst_val *)&pre_pp_0006,
	(cst_val *)&pre_pp_0007,
	(cst_val *)&pre_pp_0008,
	(cst_val *)&pre_pp_0009,
	(cst_val *)&pre_pp_0010,
	(cst_val *)&pre_pp_0011,
	(cst_val *)&pre_pp_0012,
	(cst_val *)&pre_pp_0013,
	(cst_val *)&pre_pp_0014,
	(cst_val *)&pre_pp_0015,
	(cst_val *)&pre_pp_0016,
	(cst_val *)&pre_pp_0017,
	(cst_val *)&pre_pp_0018,
	(cst_val *)&pre_pp_0019,
	(cst_val *)&pre_pp_0020,
	(cst_val *)&pre_pp_0021,
	(cst_val *)&pre_pp_0022,
	(cst_val *)&pre_pp_0023,
	(cst_val *)&pre_pp_0024,
	(cst_val *)&pre_pp_0025,
	(cst_val *)&pre_pp_0026,
	(cst_val *)&pre_pp_0027,
	(cst_val *)&pre_pp_0028,
	(cst_val *)&pre_pp_0029,
	(cst_val *)&pre_pp_0030,
	(cst_val *)&pre_pp_0031,
	(cst_val *)&pre_pp_0032,
	(cst_val *)&pre_pp_0033,
	(cst_val *)&pre_pp_0034,
	(cst_val *)&pre_pp_0035,
	(cst_val *)&pre_pp_0036,
	(cst_val *)&pre_pp_0037,
	(cst_val *)&pre_pp_0038,
	(cst_val *)&pre_pp_0039,
	(cst_val *)&pre_pp_0040,
	(cst_val *)&pre_pp_0041,
	(cst_val *)&pre_pp_0042,
	(cst_val *)&pre_pp_0043,
	0 };


DEF_STATIC_CONST_VAL_STRING(dadj_pos_0001,"dadj_pos");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0002,"mio");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0003,"mia");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0004,"mie");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0005,"miei");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0006,"tuo");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0007,"tua");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0008,"tue");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0009,"tuoi");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0010,"suo");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0011,"sua");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0012,"sue");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0013,"suoi");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0014,"nostro");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0015,"nostra");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0016,"nostre");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0017,"nostri");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0018,"vostro");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0019,"vostra");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0020,"vostre");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0021,"vostri");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0022,"loro");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0023,"altrui");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0024,"proprio");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0025,"propria");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0026,"proprie");
DEF_STATIC_CONST_VAL_STRING(dadj_pos_0027,"propri");

static const cst_val * const gpos_dadj_pos_list[] = {
	(cst_val *)&dadj_pos_0001,
	(cst_val *)&dadj_pos_0002,
	(cst_val *)&dadj_pos_0003,
	(cst_val *)&dadj_pos_0004,
	(cst_val *)&dadj_pos_0005,
	(cst_val *)&dadj_pos_0006,
	(cst_val *)&dadj_pos_0007,
	(cst_val *)&dadj_pos_0008,
	(cst_val *)&dadj_pos_0009,
	(cst_val *)&dadj_pos_0010,
	(cst_val *)&dadj_pos_0011,
	(cst_val *)&dadj_pos_0012,
	(cst_val *)&dadj_pos_0013,
	(cst_val *)&dadj_pos_0014,
	(cst_val *)&dadj_pos_0015,
	(cst_val *)&dadj_pos_0016,
	(cst_val *)&dadj_pos_0017,
	(cst_val *)&dadj_pos_0018,
	(cst_val *)&dadj_pos_0019,
	(cst_val *)&dadj_pos_0020,
	(cst_val *)&dadj_pos_0021,
	(cst_val *)&dadj_pos_0022,
	(cst_val *)&dadj_pos_0023,
	(cst_val *)&dadj_pos_0024,
	(cst_val *)&dadj_pos_0025,
	(cst_val *)&dadj_pos_0026,
	(cst_val *)&dadj_pos_0027,
	0 };


DEF_STATIC_CONST_VAL_STRING(dadj_dem_0001,"dadj_dem");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0002,"questo");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0003,"questa");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0004,"queste");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0005,"questi");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0006,"quello");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0007,"quel");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0008,"quella");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0009,"quelle");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0010,"quelli");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0011,"stesso");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0012,"stessa");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0013,"stesse");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0014,"stessi");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0015,"altro");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0016,"altra");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0017,"altre");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0018,"altri");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0019,"medesimo");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0020,"medesima");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0021,"medesime");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0022,"medesimi");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0023,"tale");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0024,"cotale");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0025,"codesto");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0026,"codesta");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0027,"codeste");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0028,"codesti");
DEF_STATIC_CONST_VAL_STRING(dadj_dem_0029,"siffatto");

static const cst_val * const gpos_dadj_dem_list[] = {
	(cst_val *)&dadj_dem_0001,
	(cst_val *)&dadj_dem_0002,
	(cst_val *)&dadj_dem_0003,
	(cst_val *)&dadj_dem_0004,
	(cst_val *)&dadj_dem_0005,
	(cst_val *)&dadj_dem_0006,
	(cst_val *)&dadj_dem_0007,
	(cst_val *)&dadj_dem_0008,
	(cst_val *)&dadj_dem_0009,
	(cst_val *)&dadj_dem_0010,
	(cst_val *)&dadj_dem_0011,
	(cst_val *)&dadj_dem_0012,
	(cst_val *)&dadj_dem_0013,
	(cst_val *)&dadj_dem_0014,
	(cst_val *)&dadj_dem_0015,
	(cst_val *)&dadj_dem_0016,
	(cst_val *)&dadj_dem_0017,
	(cst_val *)&dadj_dem_0018,
	(cst_val *)&dadj_dem_0019,
	(cst_val *)&dadj_dem_0020,
	(cst_val *)&dadj_dem_0021,
	(cst_val *)&dadj_dem_0022,
	(cst_val *)&dadj_dem_0023,
	(cst_val *)&dadj_dem_0024,
	(cst_val *)&dadj_dem_0025,
	(cst_val *)&dadj_dem_0026,
	(cst_val *)&dadj_dem_0027,
	(cst_val *)&dadj_dem_0028,
	(cst_val *)&dadj_dem_0029,
	0 };


DEF_STATIC_CONST_VAL_STRING(dadj_int_0001,"dadj_int");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0002,"che");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0003,"quale");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0004,"qual");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0005,"quanto");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0006,"quanta");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0007,"quante");
DEF_STATIC_CONST_VAL_STRING(dadj_int_0008,"quanti");

static const cst_val * const gpos_dadj_int_list[] = {
	(cst_val *)&dadj_int_0001,
	(cst_val *)&dadj_int_0002,
	(cst_val *)&dadj_int_0003,
	(cst_val *)&dadj_int_0004,
	(cst_val *)&dadj_int_0005,
	(cst_val *)&dadj_int_0006,
	(cst_val *)&dadj_int_0007,
	(cst_val *)&dadj_int_0008,
	0 };


DEF_STATIC_CONST_VAL_STRING(dadj_ind_0001,"dadj_ind");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0002,"alcun");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0003,"alcuno");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0004,"alcuna");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0005,"alcune");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0006,"alcuni");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0007,"altro");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0008,"altra");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0009,"altre");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0010,"altri");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0011,"alquanto");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0012,"alquanta");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0013,"alquante");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0014,"alquanti");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0015,"altrettanto");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0016,"altrettanta");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0017,"altrettante");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0018,"altrettanti");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0019,"certo");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0020,"certa");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0021,"certe");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0022,"certi");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0023,"diverso");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0024,"diversa");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0025,"diverse");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0026,"diversi");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0027,"molto");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0028,"molta");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0029,"molte");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0030,"molti");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0031,"parecchio");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0032,"parecchia");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0033,"parecchie");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0034,"parecchi");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0035,"poco");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0036,"poca");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0037,"poche");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0038,"pochi");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0039,"quanto");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0040,"quanta");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0041,"quante");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0042,"quanti");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0043,"taluno");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0044,"taluna");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0045,"talune");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0046,"taluni");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0047,"tanto");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0048,"tanta");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0049,"tante");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0050,"tanti");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0051,"troppo");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0052,"troppa");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0053,"troppe");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0054,"troppi");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0055,"tutto");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0056,"tutta");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0057,"tutte");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0058,"tutti");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0059,"ciascun");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0060,"ciascuno");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0061,"ciascuna");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0062,"nessuno");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0063,"nessun");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0064,"nessuna");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0065,"niuno");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0066,"niuna");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0067,"tale");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0068,"ogni");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0069,"qualche");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0070,"qualunque");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0071,"qualsiasi");
DEF_STATIC_CONST_VAL_STRING(dadj_ind_0072,"qualsivoglia");

static const cst_val * const gpos_dadj_ind_list[] = {
	(cst_val *)&dadj_ind_0001,
	(cst_val *)&dadj_ind_0002,
	(cst_val *)&dadj_ind_0003,
	(cst_val *)&dadj_ind_0004,
	(cst_val *)&dadj_ind_0005,
	(cst_val *)&dadj_ind_0006,
	(cst_val *)&dadj_ind_0007,
	(cst_val *)&dadj_ind_0008,
	(cst_val *)&dadj_ind_0009,
	(cst_val *)&dadj_ind_0010,
	(cst_val *)&dadj_ind_0011,
	(cst_val *)&dadj_ind_0012,
	(cst_val *)&dadj_ind_0013,
	(cst_val *)&dadj_ind_0014,
	(cst_val *)&dadj_ind_0015,
	(cst_val *)&dadj_ind_0016,
	(cst_val *)&dadj_ind_0017,
	(cst_val *)&dadj_ind_0018,
	(cst_val *)&dadj_ind_0019,
	(cst_val *)&dadj_ind_0020,
	(cst_val *)&dadj_ind_0021,
	(cst_val *)&dadj_ind_0022,
	(cst_val *)&dadj_ind_0023,
	(cst_val *)&dadj_ind_0024,
	(cst_val *)&dadj_ind_0025,
	(cst_val *)&dadj_ind_0026,
	(cst_val *)&dadj_ind_0027,
	(cst_val *)&dadj_ind_0028,
	(cst_val *)&dadj_ind_0029,
	(cst_val *)&dadj_ind_0030,
	(cst_val *)&dadj_ind_0031,
	(cst_val *)&dadj_ind_0032,
	(cst_val *)&dadj_ind_0033,
	(cst_val *)&dadj_ind_0034,
	(cst_val *)&dadj_ind_0035,
	(cst_val *)&dadj_ind_0036,
	(cst_val *)&dadj_ind_0037,
	(cst_val *)&dadj_ind_0038,
	(cst_val *)&dadj_ind_0039,
	(cst_val *)&dadj_ind_0040,
	(cst_val *)&dadj_ind_0041,
	(cst_val *)&dadj_ind_0042,
	(cst_val *)&dadj_ind_0043,
	(cst_val *)&dadj_ind_0044,
	(cst_val *)&dadj_ind_0045,
	(cst_val *)&dadj_ind_0046,
	(cst_val *)&dadj_ind_0047,
	(cst_val *)&dadj_ind_0048,
	(cst_val *)&dadj_ind_0049,
	(cst_val *)&dadj_ind_0050,
	(cst_val *)&dadj_ind_0051,
	(cst_val *)&dadj_ind_0052,
	(cst_val *)&dadj_ind_0053,
	(cst_val *)&dadj_ind_0054,
	(cst_val *)&dadj_ind_0055,
	(cst_val *)&dadj_ind_0056,
	(cst_val *)&dadj_ind_0057,
	(cst_val *)&dadj_ind_0058,
	(cst_val *)&dadj_ind_0059,
	(cst_val *)&dadj_ind_0060,
	(cst_val *)&dadj_ind_0061,
	(cst_val *)&dadj_ind_0062,
	(cst_val *)&dadj_ind_0063,
	(cst_val *)&dadj_ind_0064,
	(cst_val *)&dadj_ind_0065,
	(cst_val *)&dadj_ind_0066,
	(cst_val *)&dadj_ind_0067,
	(cst_val *)&dadj_ind_0068,
	(cst_val *)&dadj_ind_0069,
	(cst_val *)&dadj_ind_0070,
	(cst_val *)&dadj_ind_0071,
	(cst_val *)&dadj_ind_0072,
	0 };


DEF_STATIC_CONST_VAL_STRING(dadj_num_0001,"dadj_num");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0002,"uno");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0003,"un");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0004,"una");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0005,"due");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0006,"undici");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0007,"venti");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0008,"cento");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0009,"primo");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0010,"prima");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0011,"prime");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0012,"primi");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0013,"secondo");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0014,"seconda");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0015,"sedonde");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0016,"secondi");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0017,"decimo");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0018,"decima");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0019,"centesimo");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0020,"centesima");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0021,"doppio");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0022,"doppia");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0023,"doppie");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0024,"doppi");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0025,"duplice");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0026,"centuplo");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0027,"centuplice");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0028,"ambo");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0029,"ambedue");
DEF_STATIC_CONST_VAL_STRING(dadj_num_0030,"entrambi");

static const cst_val * const gpos_dadj_num_list[] = {
	(cst_val *)&dadj_num_0001,
	(cst_val *)&dadj_num_0002,
	(cst_val *)&dadj_num_0003,
	(cst_val *)&dadj_num_0004,
	(cst_val *)&dadj_num_0005,
	(cst_val *)&dadj_num_0006,
	(cst_val *)&dadj_num_0007,
	(cst_val *)&dadj_num_0008,
	(cst_val *)&dadj_num_0009,
	(cst_val *)&dadj_num_0010,
	(cst_val *)&dadj_num_0011,
	(cst_val *)&dadj_num_0012,
	(cst_val *)&dadj_num_0013,
	(cst_val *)&dadj_num_0014,
	(cst_val *)&dadj_num_0015,
	(cst_val *)&dadj_num_0016,
	(cst_val *)&dadj_num_0017,
	(cst_val *)&dadj_num_0018,
	(cst_val *)&dadj_num_0019,
	(cst_val *)&dadj_num_0020,
	(cst_val *)&dadj_num_0021,
	(cst_val *)&dadj_num_0022,
	(cst_val *)&dadj_num_0023,
	(cst_val *)&dadj_num_0024,
	(cst_val *)&dadj_num_0025,
	(cst_val *)&dadj_num_0026,
	(cst_val *)&dadj_num_0027,
	(cst_val *)&dadj_num_0028,
	(cst_val *)&dadj_num_0029,
	(cst_val *)&dadj_num_0030,
	0 };


DEF_STATIC_CONST_VAL_STRING(prono_per_0001,"prono_per");
DEF_STATIC_CONST_VAL_STRING(prono_per_0002,"io");
DEF_STATIC_CONST_VAL_STRING(prono_per_0003,"me");
DEF_STATIC_CONST_VAL_STRING(prono_per_0004,"mi");
DEF_STATIC_CONST_VAL_STRING(prono_per_0005,"tu");
DEF_STATIC_CONST_VAL_STRING(prono_per_0006,"te");
DEF_STATIC_CONST_VAL_STRING(prono_per_0007,"ti");
DEF_STATIC_CONST_VAL_STRING(prono_per_0008,"noi");
DEF_STATIC_CONST_VAL_STRING(prono_per_0009,"ce");
DEF_STATIC_CONST_VAL_STRING(prono_per_0010,"ci");
DEF_STATIC_CONST_VAL_STRING(prono_per_0011,"voi");
DEF_STATIC_CONST_VAL_STRING(prono_per_0012,"ve");
DEF_STATIC_CONST_VAL_STRING(prono_per_0013,"vi");
DEF_STATIC_CONST_VAL_STRING(prono_per_0014,"egli");
DEF_STATIC_CONST_VAL_STRING(prono_per_0015,"ella");
DEF_STATIC_CONST_VAL_STRING(prono_per_0016,"esso");
DEF_STATIC_CONST_VAL_STRING(prono_per_0017,"essa");
DEF_STATIC_CONST_VAL_STRING(prono_per_0018,"esse");
DEF_STATIC_CONST_VAL_STRING(prono_per_0019,"essi");
DEF_STATIC_CONST_VAL_STRING(prono_per_0020,"loro");
DEF_STATIC_CONST_VAL_STRING(prono_per_0021,"lui");
DEF_STATIC_CONST_VAL_STRING(prono_per_0022,"gli");
DEF_STATIC_CONST_VAL_STRING(prono_per_0023,"se");
DEF_STATIC_CONST_VAL_STRING(prono_per_0024,"si");
DEF_STATIC_CONST_VAL_STRING(prono_per_0025,"ne");
DEF_STATIC_CONST_VAL_STRING(prono_per_0026,"lei");
DEF_STATIC_CONST_VAL_STRING(prono_per_0027,"la");
DEF_STATIC_CONST_VAL_STRING(prono_per_0028,"le");
DEF_STATIC_CONST_VAL_STRING(prono_per_0029,"li");
DEF_STATIC_CONST_VAL_STRING(prono_per_0030,"sè");

static const cst_val * const gpos_prono_per_list[] = {
	(cst_val *)&prono_per_0001,
	(cst_val *)&prono_per_0002,
	(cst_val *)&prono_per_0003,
	(cst_val *)&prono_per_0004,
	(cst_val *)&prono_per_0005,
	(cst_val *)&prono_per_0006,
	(cst_val *)&prono_per_0007,
	(cst_val *)&prono_per_0008,
	(cst_val *)&prono_per_0009,
	(cst_val *)&prono_per_0010,
	(cst_val *)&prono_per_0011,
	(cst_val *)&prono_per_0012,
	(cst_val *)&prono_per_0013,
	(cst_val *)&prono_per_0014,
	(cst_val *)&prono_per_0015,
	(cst_val *)&prono_per_0016,
	(cst_val *)&prono_per_0017,
	(cst_val *)&prono_per_0018,
	(cst_val *)&prono_per_0019,
	(cst_val *)&prono_per_0020,
	(cst_val *)&prono_per_0021,
	(cst_val *)&prono_per_0022,
	(cst_val *)&prono_per_0023,
	(cst_val *)&prono_per_0024,
	(cst_val *)&prono_per_0025,
	(cst_val *)&prono_per_0026,
	(cst_val *)&prono_per_0027,
	(cst_val *)&prono_per_0028,
	(cst_val *)&prono_per_0029,
	(cst_val *)&prono_per_0030,
	0 };


DEF_STATIC_CONST_VAL_STRING(prono_dem_0001,"prono_dem");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0002,"lo");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0003,"la");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0004,"le");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0005,"li");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0006,"ne");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0007,"ci");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0008,"ciò");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0009,"coloro");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0010,"colui");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0011,"colei");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0012,"tale");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0013,"costui");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0014,"costei");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0015,"costoro");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0016,"questo");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0017,"questa");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0018,"queste");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0019,"questi");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0020,"codesto");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0021,"codesta");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0022,"codeste");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0023,"codesti");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0024,"quello");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0025,"quelle");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0026,"quella");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0027,"quelli");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0028,"stesso");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0029,"stessa");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0030,"stesse");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0031,"stessi");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0032,"medesimo");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0033,"medesima");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0034,"medesime");
DEF_STATIC_CONST_VAL_STRING(prono_dem_0035,"medesimi");

static const cst_val * const gpos_prono_dem_list[] = {
	(cst_val *)&prono_dem_0001,
	(cst_val *)&prono_dem_0002,
	(cst_val *)&prono_dem_0003,
	(cst_val *)&prono_dem_0004,
	(cst_val *)&prono_dem_0005,
	(cst_val *)&prono_dem_0006,
	(cst_val *)&prono_dem_0007,
	(cst_val *)&prono_dem_0008,
	(cst_val *)&prono_dem_0009,
	(cst_val *)&prono_dem_0010,
	(cst_val *)&prono_dem_0011,
	(cst_val *)&prono_dem_0012,
	(cst_val *)&prono_dem_0013,
	(cst_val *)&prono_dem_0014,
	(cst_val *)&prono_dem_0015,
	(cst_val *)&prono_dem_0016,
	(cst_val *)&prono_dem_0017,
	(cst_val *)&prono_dem_0018,
	(cst_val *)&prono_dem_0019,
	(cst_val *)&prono_dem_0020,
	(cst_val *)&prono_dem_0021,
	(cst_val *)&prono_dem_0022,
	(cst_val *)&prono_dem_0023,
	(cst_val *)&prono_dem_0024,
	(cst_val *)&prono_dem_0025,
	(cst_val *)&prono_dem_0026,
	(cst_val *)&prono_dem_0027,
	(cst_val *)&prono_dem_0028,
	(cst_val *)&prono_dem_0029,
	(cst_val *)&prono_dem_0030,
	(cst_val *)&prono_dem_0031,
	(cst_val *)&prono_dem_0032,
	(cst_val *)&prono_dem_0033,
	(cst_val *)&prono_dem_0034,
	(cst_val *)&prono_dem_0035,
	0 };


DEF_STATIC_CONST_VAL_STRING(prono_int_0001,"prono_int");
DEF_STATIC_CONST_VAL_STRING(prono_int_0002,"chi");
DEF_STATIC_CONST_VAL_STRING(prono_int_0003,"che");
DEF_STATIC_CONST_VAL_STRING(prono_int_0004,"quale");
DEF_STATIC_CONST_VAL_STRING(prono_int_0005,"quanto");

static const cst_val * const gpos_prono_int_list[] = {
	(cst_val *)&prono_int_0001,
	(cst_val *)&prono_int_0002,
	(cst_val *)&prono_int_0003,
	(cst_val *)&prono_int_0004,
	(cst_val *)&prono_int_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(prono_rel_0001,"prono_rel");
DEF_STATIC_CONST_VAL_STRING(prono_rel_0002,"che");
DEF_STATIC_CONST_VAL_STRING(prono_rel_0003,"il");
DEF_STATIC_CONST_VAL_STRING(prono_rel_0004,"quale");
DEF_STATIC_CONST_VAL_STRING(prono_rel_0005,"cui");

static const cst_val * const gpos_prono_rel_list[] = {
	(cst_val *)&prono_rel_0001,
	(cst_val *)&prono_rel_0002,
	(cst_val *)&prono_rel_0003,
	(cst_val *)&prono_rel_0004,
	(cst_val *)&prono_rel_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(prono_mix_0001,"prono_mix");
DEF_STATIC_CONST_VAL_STRING(prono_mix_0002,"chi");
DEF_STATIC_CONST_VAL_STRING(prono_mix_0003,"quanto");
DEF_STATIC_CONST_VAL_STRING(prono_mix_0004,"chiunque");

static const cst_val * const gpos_prono_mix_list[] = {
	(cst_val *)&prono_mix_0001,
	(cst_val *)&prono_mix_0002,
	(cst_val *)&prono_mix_0003,
	(cst_val *)&prono_mix_0004,
	0 };


DEF_STATIC_CONST_VAL_STRING(prono_ind_0001,"prono_ind");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0002,"uno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0003,"un");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0004,"una");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0005,"qualcuno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0006,"qualcuna");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0007,"qualcosa");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0008,"ognuno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0009,"ognuna");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0010,"niente");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0011,"nulla");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0012,"altri");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0013,"certuni");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0014,"chicchessia");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0015,"checchessia");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0016,"alcuno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0017,"alcuna");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0018,"alcune");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0019,"alcuni");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0020,"ciascuno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0021,"ciascuna");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0022,"taluno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0023,"taluni");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0024,"altro");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0025,"altra");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0026,"altre");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0027,"altri");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0028,"certo");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0029,"certa");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0030,"certe");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0031,"certi");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0032,"nessuno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0033,"nessun");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0034,"nessuna");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0035,"veruno");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0036,"poco");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0037,"molto");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0038,"parecchio");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0039,"troppo");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0040,"tutto");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0041,"tanto");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0042,"quanto");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0043,"alquanto");
DEF_STATIC_CONST_VAL_STRING(prono_ind_0044,"altrettanto");

static const cst_val * const gpos_prono_ind_list[] = {
	(cst_val *)&prono_ind_0001,
	(cst_val *)&prono_ind_0002,
	(cst_val *)&prono_ind_0003,
	(cst_val *)&prono_ind_0004,
	(cst_val *)&prono_ind_0005,
	(cst_val *)&prono_ind_0006,
	(cst_val *)&prono_ind_0007,
	(cst_val *)&prono_ind_0008,
	(cst_val *)&prono_ind_0009,
	(cst_val *)&prono_ind_0010,
	(cst_val *)&prono_ind_0011,
	(cst_val *)&prono_ind_0012,
	(cst_val *)&prono_ind_0013,
	(cst_val *)&prono_ind_0014,
	(cst_val *)&prono_ind_0015,
	(cst_val *)&prono_ind_0016,
	(cst_val *)&prono_ind_0017,
	(cst_val *)&prono_ind_0018,
	(cst_val *)&prono_ind_0019,
	(cst_val *)&prono_ind_0020,
	(cst_val *)&prono_ind_0021,
	(cst_val *)&prono_ind_0022,
	(cst_val *)&prono_ind_0023,
	(cst_val *)&prono_ind_0024,
	(cst_val *)&prono_ind_0025,
	(cst_val *)&prono_ind_0026,
	(cst_val *)&prono_ind_0027,
	(cst_val *)&prono_ind_0028,
	(cst_val *)&prono_ind_0029,
	(cst_val *)&prono_ind_0030,
	(cst_val *)&prono_ind_0031,
	(cst_val *)&prono_ind_0032,
	(cst_val *)&prono_ind_0033,
	(cst_val *)&prono_ind_0034,
	(cst_val *)&prono_ind_0035,
	(cst_val *)&prono_ind_0036,
	(cst_val *)&prono_ind_0037,
	(cst_val *)&prono_ind_0038,
	(cst_val *)&prono_ind_0039,
	(cst_val *)&prono_ind_0040,
	(cst_val *)&prono_ind_0041,
	(cst_val *)&prono_ind_0042,
	(cst_val *)&prono_ind_0043,
	(cst_val *)&prono_ind_0044,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0001,"conjcoo_cop");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0002,"e");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0003,"ed");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0004,"anche");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0005,"nè");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0006,"neppure");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0007,"neanche");
DEF_STATIC_CONST_VAL_STRING(conjcoo_cop_0008,"nemmeno");

static const cst_val * const gpos_conjcoo_cop_list[] = {
	(cst_val *)&conjcoo_cop_0001,
	(cst_val *)&conjcoo_cop_0002,
	(cst_val *)&conjcoo_cop_0003,
	(cst_val *)&conjcoo_cop_0004,
	(cst_val *)&conjcoo_cop_0005,
	(cst_val *)&conjcoo_cop_0006,
	(cst_val *)&conjcoo_cop_0007,
	(cst_val *)&conjcoo_cop_0008,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_dis_0001,"conjcoo_dis");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dis_0002,"o");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dis_0003,"ossia");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dis_0004,"ovvero");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dis_0005,"oppure");

static const cst_val * const gpos_conjcoo_dis_list[] = {
	(cst_val *)&conjcoo_dis_0001,
	(cst_val *)&conjcoo_dis_0002,
	(cst_val *)&conjcoo_dis_0003,
	(cst_val *)&conjcoo_dis_0004,
	(cst_val *)&conjcoo_dis_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0001,"conjcoo_adv");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0002,"ma");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0003,"però");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0004,"invece");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0005,"tuttavia");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0006,"cionondimeno");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0007,"pure");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0008,"peraltro");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0009,"con");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0010,"tutto");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adv_0011,"ciò");

static const cst_val * const gpos_conjcoo_adv_list[] = {
	(cst_val *)&conjcoo_adv_0001,
	(cst_val *)&conjcoo_adv_0002,
	(cst_val *)&conjcoo_adv_0003,
	(cst_val *)&conjcoo_adv_0004,
	(cst_val *)&conjcoo_adv_0005,
	(cst_val *)&conjcoo_adv_0006,
	(cst_val *)&conjcoo_adv_0007,
	(cst_val *)&conjcoo_adv_0008,
	(cst_val *)&conjcoo_adv_0009,
	(cst_val *)&conjcoo_adv_0010,
	(cst_val *)&conjcoo_adv_0011,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0001,"conjcoo_dec");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0002,"cioè");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0003,"infatti");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0004,"ossia");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0005,"invero");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0006,"vale");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0007,"a");
DEF_STATIC_CONST_VAL_STRING(conjcoo_dec_0008,"dire");

static const cst_val * const gpos_conjcoo_dec_list[] = {
	(cst_val *)&conjcoo_dec_0001,
	(cst_val *)&conjcoo_dec_0002,
	(cst_val *)&conjcoo_dec_0003,
	(cst_val *)&conjcoo_dec_0004,
	(cst_val *)&conjcoo_dec_0005,
	(cst_val *)&conjcoo_dec_0006,
	(cst_val *)&conjcoo_dec_0007,
	(cst_val *)&conjcoo_dec_0008,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0001,"conjcoo_con");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0002,"dunque");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0003,"perciò");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0004,"pertanto");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0005,"quindi");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0006,"sicchè");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0007,"per");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0008,"la");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0009,"qual");
DEF_STATIC_CONST_VAL_STRING(conjcoo_con_0010,"cosa");

static const cst_val * const gpos_conjcoo_con_list[] = {
	(cst_val *)&conjcoo_con_0001,
	(cst_val *)&conjcoo_con_0002,
	(cst_val *)&conjcoo_con_0003,
	(cst_val *)&conjcoo_con_0004,
	(cst_val *)&conjcoo_con_0005,
	(cst_val *)&conjcoo_con_0006,
	(cst_val *)&conjcoo_con_0007,
	(cst_val *)&conjcoo_con_0008,
	(cst_val *)&conjcoo_con_0009,
	(cst_val *)&conjcoo_con_0010,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0001,"conjcoo_adj");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0002,"inoltre");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0003,"pure");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0004,"ancora");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0005,"oltre");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0006,"a");
DEF_STATIC_CONST_VAL_STRING(conjcoo_adj_0007,"ciò");

static const cst_val * const gpos_conjcoo_adj_list[] = {
	(cst_val *)&conjcoo_adj_0001,
	(cst_val *)&conjcoo_adj_0002,
	(cst_val *)&conjcoo_adj_0003,
	(cst_val *)&conjcoo_adj_0004,
	(cst_val *)&conjcoo_adj_0005,
	(cst_val *)&conjcoo_adj_0006,
	(cst_val *)&conjcoo_adj_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0001,"conjcoo_corr");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0002,"e");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0003,"nè");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0004,"o");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0005,"come");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0006,"così");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0007,"tanto");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0008,"quanto");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0009,"non");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0010,"solo");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0011,"ma");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0012,"anche");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0013,"tanto");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0014,"più");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0015,"quanto");
DEF_STATIC_CONST_VAL_STRING(conjcoo_corr_0016,"più");

static const cst_val * const gpos_conjcoo_corr_list[] = {
	(cst_val *)&conjcoo_corr_0001,
	(cst_val *)&conjcoo_corr_0002,
	(cst_val *)&conjcoo_corr_0003,
	(cst_val *)&conjcoo_corr_0004,
	(cst_val *)&conjcoo_corr_0005,
	(cst_val *)&conjcoo_corr_0006,
	(cst_val *)&conjcoo_corr_0007,
	(cst_val *)&conjcoo_corr_0008,
	(cst_val *)&conjcoo_corr_0009,
	(cst_val *)&conjcoo_corr_0010,
	(cst_val *)&conjcoo_corr_0011,
	(cst_val *)&conjcoo_corr_0012,
	(cst_val *)&conjcoo_corr_0013,
	(cst_val *)&conjcoo_corr_0014,
	(cst_val *)&conjcoo_corr_0015,
	(cst_val *)&conjcoo_corr_0016,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_dec_0001,"sub_dec");
DEF_STATIC_CONST_VAL_STRING(sub_dec_0002,"che");
DEF_STATIC_CONST_VAL_STRING(sub_dec_0003,"come");

static const cst_val * const gpos_sub_dec_list[] = {
	(cst_val *)&sub_dec_0001,
	(cst_val *)&sub_dec_0002,
	(cst_val *)&sub_dec_0003,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_temp_0001,"sub_temp");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0002,"quando");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0003,"come");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0004,"appena");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0005,"allorchè");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0006,"finchè");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0007,"allorquando");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0008,"nel");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0009,"tempo");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0010,"che");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0011,"tosto");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0012,"che");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0013,"prima");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0014,"che");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0015,"dopo");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0016,"che");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0017,"ognivolta");
DEF_STATIC_CONST_VAL_STRING(sub_temp_0018,"che");

static const cst_val * const gpos_sub_temp_list[] = {
	(cst_val *)&sub_temp_0001,
	(cst_val *)&sub_temp_0002,
	(cst_val *)&sub_temp_0003,
	(cst_val *)&sub_temp_0004,
	(cst_val *)&sub_temp_0005,
	(cst_val *)&sub_temp_0006,
	(cst_val *)&sub_temp_0007,
	(cst_val *)&sub_temp_0008,
	(cst_val *)&sub_temp_0009,
	(cst_val *)&sub_temp_0010,
	(cst_val *)&sub_temp_0011,
	(cst_val *)&sub_temp_0012,
	(cst_val *)&sub_temp_0013,
	(cst_val *)&sub_temp_0014,
	(cst_val *)&sub_temp_0015,
	(cst_val *)&sub_temp_0016,
	(cst_val *)&sub_temp_0017,
	(cst_val *)&sub_temp_0018,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_caus_0001,"sub_caus");
DEF_STATIC_CONST_VAL_STRING(sub_caus_0002,"poichè");
DEF_STATIC_CONST_VAL_STRING(sub_caus_0003,"perchè");
DEF_STATIC_CONST_VAL_STRING(sub_caus_0004,"giacchè");
DEF_STATIC_CONST_VAL_STRING(sub_caus_0005,"siccome");
DEF_STATIC_CONST_VAL_STRING(sub_caus_0006,"dato");
DEF_STATIC_CONST_VAL_STRING(sub_caus_0007,"che");

static const cst_val * const gpos_sub_caus_list[] = {
	(cst_val *)&sub_caus_0001,
	(cst_val *)&sub_caus_0002,
	(cst_val *)&sub_caus_0003,
	(cst_val *)&sub_caus_0004,
	(cst_val *)&sub_caus_0005,
	(cst_val *)&sub_caus_0006,
	(cst_val *)&sub_caus_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_fin_0001,"sub_fin");
DEF_STATIC_CONST_VAL_STRING(sub_fin_0002,"affinchè");
DEF_STATIC_CONST_VAL_STRING(sub_fin_0003,"perchè");
DEF_STATIC_CONST_VAL_STRING(sub_fin_0004,"acciochè");

static const cst_val * const gpos_sub_fin_list[] = {
	(cst_val *)&sub_fin_0001,
	(cst_val *)&sub_fin_0002,
	(cst_val *)&sub_fin_0003,
	(cst_val *)&sub_fin_0004,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_cond_0001,"sub_cond");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0002,"se");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0003,"purchè");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0004,"qualora");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0005,"posto");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0006,"che");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0007,"in");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0008,"caso");
DEF_STATIC_CONST_VAL_STRING(sub_cond_0009,"che");

static const cst_val * const gpos_sub_cond_list[] = {
	(cst_val *)&sub_cond_0001,
	(cst_val *)&sub_cond_0002,
	(cst_val *)&sub_cond_0003,
	(cst_val *)&sub_cond_0004,
	(cst_val *)&sub_cond_0005,
	(cst_val *)&sub_cond_0006,
	(cst_val *)&sub_cond_0007,
	(cst_val *)&sub_cond_0008,
	(cst_val *)&sub_cond_0009,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_conc_0001,"sub_conc");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0002,"benchè");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0003,"quantunque");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0004,"sebbene");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0005,"anche");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0006,"se");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0007,"per");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0008,"quanto");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0009,"nonostante");
DEF_STATIC_CONST_VAL_STRING(sub_conc_0010,"che");

static const cst_val * const gpos_sub_conc_list[] = {
	(cst_val *)&sub_conc_0001,
	(cst_val *)&sub_conc_0002,
	(cst_val *)&sub_conc_0003,
	(cst_val *)&sub_conc_0004,
	(cst_val *)&sub_conc_0005,
	(cst_val *)&sub_conc_0006,
	(cst_val *)&sub_conc_0007,
	(cst_val *)&sub_conc_0008,
	(cst_val *)&sub_conc_0009,
	(cst_val *)&sub_conc_0010,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_cons_0001,"sub_cons");
DEF_STATIC_CONST_VAL_STRING(sub_cons_0002,"sicchè");
DEF_STATIC_CONST_VAL_STRING(sub_cons_0003,"tale");
DEF_STATIC_CONST_VAL_STRING(sub_cons_0004,"che");

static const cst_val * const gpos_sub_cons_list[] = {
	(cst_val *)&sub_cons_0001,
	(cst_val *)&sub_cons_0002,
	(cst_val *)&sub_cons_0003,
	(cst_val *)&sub_cons_0004,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_comp_0001,"sub_comp");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0002,"così");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0003,"come");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0004,"tanto");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0005,"come");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0006,"più");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0007,"che");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0008,"meglio");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0009,"che");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0010,"piuttosto");
DEF_STATIC_CONST_VAL_STRING(sub_comp_0011,"che");

static const cst_val * const gpos_sub_comp_list[] = {
	(cst_val *)&sub_comp_0001,
	(cst_val *)&sub_comp_0002,
	(cst_val *)&sub_comp_0003,
	(cst_val *)&sub_comp_0004,
	(cst_val *)&sub_comp_0005,
	(cst_val *)&sub_comp_0006,
	(cst_val *)&sub_comp_0007,
	(cst_val *)&sub_comp_0008,
	(cst_val *)&sub_comp_0009,
	(cst_val *)&sub_comp_0010,
	(cst_val *)&sub_comp_0011,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_mod_0001,"sub_mod");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0002,"come");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0003,"siccome");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0004,"quasi");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0005,"comunque");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0006,"a");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0007,"quel");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0008,"modo");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0009,"che");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0010,"secondo");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0011,"che");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0012,"come");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0013,"se");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0014,"quasi");
DEF_STATIC_CONST_VAL_STRING(sub_mod_0015,"che");

static const cst_val * const gpos_sub_mod_list[] = {
	(cst_val *)&sub_mod_0001,
	(cst_val *)&sub_mod_0002,
	(cst_val *)&sub_mod_0003,
	(cst_val *)&sub_mod_0004,
	(cst_val *)&sub_mod_0005,
	(cst_val *)&sub_mod_0006,
	(cst_val *)&sub_mod_0007,
	(cst_val *)&sub_mod_0008,
	(cst_val *)&sub_mod_0009,
	(cst_val *)&sub_mod_0010,
	(cst_val *)&sub_mod_0011,
	(cst_val *)&sub_mod_0012,
	(cst_val *)&sub_mod_0013,
	(cst_val *)&sub_mod_0014,
	(cst_val *)&sub_mod_0015,
	0 };


DEF_STATIC_CONST_VAL_STRING(sub_exc_0001,"sub_exc");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0002,"fuorchè");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0003,"eccetto");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0004,"che");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0005,"se");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0006,"non");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0007,"che");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0008,"salvo");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0009,"che");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0010,"senza");
DEF_STATIC_CONST_VAL_STRING(sub_exc_0011,"che");

static const cst_val * const gpos_sub_exc_list[] = {
	(cst_val *)&sub_exc_0001,
	(cst_val *)&sub_exc_0002,
	(cst_val *)&sub_exc_0003,
	(cst_val *)&sub_exc_0004,
	(cst_val *)&sub_exc_0005,
	(cst_val *)&sub_exc_0006,
	(cst_val *)&sub_exc_0007,
	(cst_val *)&sub_exc_0008,
	(cst_val *)&sub_exc_0009,
	(cst_val *)&sub_exc_0010,
	(cst_val *)&sub_exc_0011,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_quan_0001,"adv_quan");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0002,"molto");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0003,"poco");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0004,"troppo");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0005,"parecchio");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0006,"alquanto");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0007,"piu");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0008,"meno");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0009,"almeno");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0010,"oltre");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0011,"misura");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0012,"all'");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0013,"incirca");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0014,"press'");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0015,"a");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0016,"poco");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0017,"pressappoco");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0018,"quasi");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0019,"circa");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0020,"punto");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0021,"assai");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0022,"abbastanza");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0023,"affatto");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0024,"altresì");
DEF_STATIC_CONST_VAL_STRING(adv_quan_0025,"oltremodo");

static const cst_val * const gpos_adv_quan_list[] = {
	(cst_val *)&adv_quan_0001,
	(cst_val *)&adv_quan_0002,
	(cst_val *)&adv_quan_0003,
	(cst_val *)&adv_quan_0004,
	(cst_val *)&adv_quan_0005,
	(cst_val *)&adv_quan_0006,
	(cst_val *)&adv_quan_0007,
	(cst_val *)&adv_quan_0008,
	(cst_val *)&adv_quan_0009,
	(cst_val *)&adv_quan_0010,
	(cst_val *)&adv_quan_0011,
	(cst_val *)&adv_quan_0012,
	(cst_val *)&adv_quan_0013,
	(cst_val *)&adv_quan_0014,
	(cst_val *)&adv_quan_0015,
	(cst_val *)&adv_quan_0016,
	(cst_val *)&adv_quan_0017,
	(cst_val *)&adv_quan_0018,
	(cst_val *)&adv_quan_0019,
	(cst_val *)&adv_quan_0020,
	(cst_val *)&adv_quan_0021,
	(cst_val *)&adv_quan_0022,
	(cst_val *)&adv_quan_0023,
	(cst_val *)&adv_quan_0024,
	(cst_val *)&adv_quan_0025,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_pla_0001,"adv_pla");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0002,"qui");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0003,"qua");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0004,"quassù");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0005,"quaggiù");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0006,"di");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0007,"qui");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0008,"costì");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0009,"costà");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0010,"lì");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0011,"là");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0012,"laggiù");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0013,"ivi");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0014,"di");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0015,"là");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0016,"per");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0017,"di");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0018,"là");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0019,"altrove");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0020,"fuori");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0021,"dappertutto");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0022,"dentro");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0023,"a");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0024,"destra");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0025,"a");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0026,"sinistra");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0027,"vicino");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0028,"lontano");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0029,"su");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0030,"giù");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0031,"oltre");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0032,"ove");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0033,"dove");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0034,"donde");
DEF_STATIC_CONST_VAL_STRING(adv_pla_0035,"dovunque");

static const cst_val * const gpos_adv_pla_list[] = {
	(cst_val *)&adv_pla_0001,
	(cst_val *)&adv_pla_0002,
	(cst_val *)&adv_pla_0003,
	(cst_val *)&adv_pla_0004,
	(cst_val *)&adv_pla_0005,
	(cst_val *)&adv_pla_0006,
	(cst_val *)&adv_pla_0007,
	(cst_val *)&adv_pla_0008,
	(cst_val *)&adv_pla_0009,
	(cst_val *)&adv_pla_0010,
	(cst_val *)&adv_pla_0011,
	(cst_val *)&adv_pla_0012,
	(cst_val *)&adv_pla_0013,
	(cst_val *)&adv_pla_0014,
	(cst_val *)&adv_pla_0015,
	(cst_val *)&adv_pla_0016,
	(cst_val *)&adv_pla_0017,
	(cst_val *)&adv_pla_0018,
	(cst_val *)&adv_pla_0019,
	(cst_val *)&adv_pla_0020,
	(cst_val *)&adv_pla_0021,
	(cst_val *)&adv_pla_0022,
	(cst_val *)&adv_pla_0023,
	(cst_val *)&adv_pla_0024,
	(cst_val *)&adv_pla_0025,
	(cst_val *)&adv_pla_0026,
	(cst_val *)&adv_pla_0027,
	(cst_val *)&adv_pla_0028,
	(cst_val *)&adv_pla_0029,
	(cst_val *)&adv_pla_0030,
	(cst_val *)&adv_pla_0031,
	(cst_val *)&adv_pla_0032,
	(cst_val *)&adv_pla_0033,
	(cst_val *)&adv_pla_0034,
	(cst_val *)&adv_pla_0035,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_time_0001,"adv_time");
DEF_STATIC_CONST_VAL_STRING(adv_time_0002,"ieri");
DEF_STATIC_CONST_VAL_STRING(adv_time_0003,"oggi");
DEF_STATIC_CONST_VAL_STRING(adv_time_0004,"domani");
DEF_STATIC_CONST_VAL_STRING(adv_time_0005,"dopodomani");
DEF_STATIC_CONST_VAL_STRING(adv_time_0006,"dopo");
DEF_STATIC_CONST_VAL_STRING(adv_time_0007,"poi");
DEF_STATIC_CONST_VAL_STRING(adv_time_0008,"precedentemente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0009,"prima");
DEF_STATIC_CONST_VAL_STRING(adv_time_0010,"sempre");
DEF_STATIC_CONST_VAL_STRING(adv_time_0011,"ora");
DEF_STATIC_CONST_VAL_STRING(adv_time_0012,"tuttora");
DEF_STATIC_CONST_VAL_STRING(adv_time_0013,"ancora");
DEF_STATIC_CONST_VAL_STRING(adv_time_0014,"finora");
DEF_STATIC_CONST_VAL_STRING(adv_time_0015,"adesso");
DEF_STATIC_CONST_VAL_STRING(adv_time_0016,"già");
DEF_STATIC_CONST_VAL_STRING(adv_time_0017,"immediatamente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0018,"subito");
DEF_STATIC_CONST_VAL_STRING(adv_time_0019,"talvolta");
DEF_STATIC_CONST_VAL_STRING(adv_time_0020,"raramente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0021,"spesso");
DEF_STATIC_CONST_VAL_STRING(adv_time_0022,"mai");
DEF_STATIC_CONST_VAL_STRING(adv_time_0023,"sovente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0024,"tardi");
DEF_STATIC_CONST_VAL_STRING(adv_time_0025,"presto");
DEF_STATIC_CONST_VAL_STRING(adv_time_0026,"quotidianamente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0027,"giornalmente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0028,"settimanalmente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0029,"mensilmente");
DEF_STATIC_CONST_VAL_STRING(adv_time_0030,"annualmente");

static const cst_val * const gpos_adv_time_list[] = {
	(cst_val *)&adv_time_0001,
	(cst_val *)&adv_time_0002,
	(cst_val *)&adv_time_0003,
	(cst_val *)&adv_time_0004,
	(cst_val *)&adv_time_0005,
	(cst_val *)&adv_time_0006,
	(cst_val *)&adv_time_0007,
	(cst_val *)&adv_time_0008,
	(cst_val *)&adv_time_0009,
	(cst_val *)&adv_time_0010,
	(cst_val *)&adv_time_0011,
	(cst_val *)&adv_time_0012,
	(cst_val *)&adv_time_0013,
	(cst_val *)&adv_time_0014,
	(cst_val *)&adv_time_0015,
	(cst_val *)&adv_time_0016,
	(cst_val *)&adv_time_0017,
	(cst_val *)&adv_time_0018,
	(cst_val *)&adv_time_0019,
	(cst_val *)&adv_time_0020,
	(cst_val *)&adv_time_0021,
	(cst_val *)&adv_time_0022,
	(cst_val *)&adv_time_0023,
	(cst_val *)&adv_time_0024,
	(cst_val *)&adv_time_0025,
	(cst_val *)&adv_time_0026,
	(cst_val *)&adv_time_0027,
	(cst_val *)&adv_time_0028,
	(cst_val *)&adv_time_0029,
	(cst_val *)&adv_time_0030,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_aff_0001,"adv_aff");
DEF_STATIC_CONST_VAL_STRING(adv_aff_0002,"si");
DEF_STATIC_CONST_VAL_STRING(adv_aff_0003,"certo");
DEF_STATIC_CONST_VAL_STRING(adv_aff_0004,"sicuro");
DEF_STATIC_CONST_VAL_STRING(adv_aff_0005,"appunto");
DEF_STATIC_CONST_VAL_STRING(adv_aff_0006,"certamente");

static const cst_val * const gpos_adv_aff_list[] = {
	(cst_val *)&adv_aff_0001,
	(cst_val *)&adv_aff_0002,
	(cst_val *)&adv_aff_0003,
	(cst_val *)&adv_aff_0004,
	(cst_val *)&adv_aff_0005,
	(cst_val *)&adv_aff_0006,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_neg_0001,"adv_neg");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0002,"no");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0003,"non");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0004,"giammai");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0005,"niente");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0006,"affatto");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0007,"nemmeno");
DEF_STATIC_CONST_VAL_STRING(adv_neg_0008,"neppure");

static const cst_val * const gpos_adv_neg_list[] = {
	(cst_val *)&adv_neg_0001,
	(cst_val *)&adv_neg_0002,
	(cst_val *)&adv_neg_0003,
	(cst_val *)&adv_neg_0004,
	(cst_val *)&adv_neg_0005,
	(cst_val *)&adv_neg_0006,
	(cst_val *)&adv_neg_0007,
	(cst_val *)&adv_neg_0008,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_pro_0001,"adv_pro");
DEF_STATIC_CONST_VAL_STRING(adv_pro_0002,"forse");
DEF_STATIC_CONST_VAL_STRING(adv_pro_0003,"probabilmente");
DEF_STATIC_CONST_VAL_STRING(adv_pro_0004,"possibilmente");
DEF_STATIC_CONST_VAL_STRING(adv_pro_0005,"eventualmente");

static const cst_val * const gpos_adv_pro_list[] = {
	(cst_val *)&adv_pro_0001,
	(cst_val *)&adv_pro_0002,
	(cst_val *)&adv_pro_0003,
	(cst_val *)&adv_pro_0004,
	(cst_val *)&adv_pro_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(adv_agg_0001,"adv_agg");
DEF_STATIC_CONST_VAL_STRING(adv_agg_0002,"anche");
DEF_STATIC_CONST_VAL_STRING(adv_agg_0003,"pure");
DEF_STATIC_CONST_VAL_STRING(adv_agg_0004,"inoltre");
DEF_STATIC_CONST_VAL_STRING(adv_agg_0005,"perfino");

static const cst_val * const gpos_adv_agg_list[] = {
	(cst_val *)&adv_agg_0001,
	(cst_val *)&adv_agg_0002,
	(cst_val *)&adv_agg_0003,
	(cst_val *)&adv_agg_0004,
	(cst_val *)&adv_agg_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_in_p_0001,"v_es_in_p");
DEF_STATIC_CONST_VAL_STRING(v_es_in_p_0002,"sono");
DEF_STATIC_CONST_VAL_STRING(v_es_in_p_0003,"sei");
DEF_STATIC_CONST_VAL_STRING(v_es_in_p_0004,"è");
DEF_STATIC_CONST_VAL_STRING(v_es_in_p_0005,"siamo");
DEF_STATIC_CONST_VAL_STRING(v_es_in_p_0006,"siete");

static const cst_val * const gpos_v_es_in_p_list[] = {
	(cst_val *)&v_es_in_p_0001,
	(cst_val *)&v_es_in_p_0002,
	(cst_val *)&v_es_in_p_0003,
	(cst_val *)&v_es_in_p_0004,
	(cst_val *)&v_es_in_p_0005,
	(cst_val *)&v_es_in_p_0006,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_in_pp_0001,"v_es_in_pp");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pp_0002,"stato");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pp_0003,"stati");

static const cst_val * const gpos_v_es_in_pp_list[] = {
	(cst_val *)&v_es_in_pp_0001,
	(cst_val *)&v_es_in_pp_0002,
	(cst_val *)&v_es_in_pp_0003,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0001,"v_es_in_pr");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0002,"fui");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0003,"fosti");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0004,"fu");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0005,"fummo");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0006,"foste");
DEF_STATIC_CONST_VAL_STRING(v_es_in_pr_0007,"furono");

static const cst_val * const gpos_v_es_in_pr_list[] = {
	(cst_val *)&v_es_in_pr_0001,
	(cst_val *)&v_es_in_pr_0002,
	(cst_val *)&v_es_in_pr_0003,
	(cst_val *)&v_es_in_pr_0004,
	(cst_val *)&v_es_in_pr_0005,
	(cst_val *)&v_es_in_pr_0006,
	(cst_val *)&v_es_in_pr_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0001,"v_es_in_i");
DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0002,"ero");
DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0003,"eri");
DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0004,"era");
DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0005,"eravamo");
DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0006,"eravate");
DEF_STATIC_CONST_VAL_STRING(v_es_in_i_0007,"erano");

static const cst_val * const gpos_v_es_in_i_list[] = {
	(cst_val *)&v_es_in_i_0001,
	(cst_val *)&v_es_in_i_0002,
	(cst_val *)&v_es_in_i_0003,
	(cst_val *)&v_es_in_i_0004,
	(cst_val *)&v_es_in_i_0005,
	(cst_val *)&v_es_in_i_0006,
	(cst_val *)&v_es_in_i_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0001,"v_es_in_f");
DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0002,"sarò");
DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0003,"sarai");
DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0004,"sarà");
DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0005,"saremo");
DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0006,"sarete");
DEF_STATIC_CONST_VAL_STRING(v_es_in_f_0007,"saranno");

static const cst_val * const gpos_v_es_in_f_list[] = {
	(cst_val *)&v_es_in_f_0001,
	(cst_val *)&v_es_in_f_0002,
	(cst_val *)&v_es_in_f_0003,
	(cst_val *)&v_es_in_f_0004,
	(cst_val *)&v_es_in_f_0005,
	(cst_val *)&v_es_in_f_0006,
	(cst_val *)&v_es_in_f_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_co_p_0001,"v_es_co_p");
DEF_STATIC_CONST_VAL_STRING(v_es_co_p_0002,"sia");
DEF_STATIC_CONST_VAL_STRING(v_es_co_p_0003,"siamo");
DEF_STATIC_CONST_VAL_STRING(v_es_co_p_0004,"siate");
DEF_STATIC_CONST_VAL_STRING(v_es_co_p_0005,"siano");

static const cst_val * const gpos_v_es_co_p_list[] = {
	(cst_val *)&v_es_co_p_0001,
	(cst_val *)&v_es_co_p_0002,
	(cst_val *)&v_es_co_p_0003,
	(cst_val *)&v_es_co_p_0004,
	(cst_val *)&v_es_co_p_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_co_i_0001,"v_es_co_i");
DEF_STATIC_CONST_VAL_STRING(v_es_co_i_0002,"fossi");
DEF_STATIC_CONST_VAL_STRING(v_es_co_i_0003,"fosse");
DEF_STATIC_CONST_VAL_STRING(v_es_co_i_0004,"fossimo");
DEF_STATIC_CONST_VAL_STRING(v_es_co_i_0005,"foste");
DEF_STATIC_CONST_VAL_STRING(v_es_co_i_0006,"fossero");

static const cst_val * const gpos_v_es_co_i_list[] = {
	(cst_val *)&v_es_co_i_0001,
	(cst_val *)&v_es_co_i_0002,
	(cst_val *)&v_es_co_i_0003,
	(cst_val *)&v_es_co_i_0004,
	(cst_val *)&v_es_co_i_0005,
	(cst_val *)&v_es_co_i_0006,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0001,"v_es_cd_p");
DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0002,"sarei");
DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0003,"saresti");
DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0004,"sarebbe");
DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0005,"saremmo");
DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0006,"sareste");
DEF_STATIC_CONST_VAL_STRING(v_es_cd_p_0007,"sarebbero");

static const cst_val * const gpos_v_es_cd_p_list[] = {
	(cst_val *)&v_es_cd_p_0001,
	(cst_val *)&v_es_cd_p_0002,
	(cst_val *)&v_es_cd_p_0003,
	(cst_val *)&v_es_cd_p_0004,
	(cst_val *)&v_es_cd_p_0005,
	(cst_val *)&v_es_cd_p_0006,
	(cst_val *)&v_es_cd_p_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_im_p_0001,"v_es_im_p");
DEF_STATIC_CONST_VAL_STRING(v_es_im_p_0002,"sii");
DEF_STATIC_CONST_VAL_STRING(v_es_im_p_0003,"sia");
DEF_STATIC_CONST_VAL_STRING(v_es_im_p_0004,"siamo");
DEF_STATIC_CONST_VAL_STRING(v_es_im_p_0005,"siate");
DEF_STATIC_CONST_VAL_STRING(v_es_im_p_0006,"siano");

static const cst_val * const gpos_v_es_im_p_list[] = {
	(cst_val *)&v_es_im_p_0001,
	(cst_val *)&v_es_im_p_0002,
	(cst_val *)&v_es_im_p_0003,
	(cst_val *)&v_es_im_p_0004,
	(cst_val *)&v_es_im_p_0005,
	(cst_val *)&v_es_im_p_0006,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_es_ge_p_0001,"v_es_ge_p");
DEF_STATIC_CONST_VAL_STRING(v_es_ge_p_0002,"essendo");

static const cst_val * const gpos_v_es_ge_p_list[] = {
	(cst_val *)&v_es_ge_p_0001,
	(cst_val *)&v_es_ge_p_0002,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0001,"v_av_in_p");
DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0002,"ho");
DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0003,"hai");
DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0004,"ha");
DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0005,"abbiamo");
DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0006,"avete");
DEF_STATIC_CONST_VAL_STRING(v_av_in_p_0007,"hanno");

static const cst_val * const gpos_v_av_in_p_list[] = {
	(cst_val *)&v_av_in_p_0001,
	(cst_val *)&v_av_in_p_0002,
	(cst_val *)&v_av_in_p_0003,
	(cst_val *)&v_av_in_p_0004,
	(cst_val *)&v_av_in_p_0005,
	(cst_val *)&v_av_in_p_0006,
	(cst_val *)&v_av_in_p_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_in_pp_0001,"v_av_in_pp");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pp_0002,"avuto");

static const cst_val * const gpos_v_av_in_pp_list[] = {
	(cst_val *)&v_av_in_pp_0001,
	(cst_val *)&v_av_in_pp_0002,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0001,"v_av_in_pr");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0002,"ebbi");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0003,"avesti");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0004,"ebbe");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0005,"avemmo");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0006,"aveste");
DEF_STATIC_CONST_VAL_STRING(v_av_in_pr_0007,"ebbero");

static const cst_val * const gpos_v_av_in_pr_list[] = {
	(cst_val *)&v_av_in_pr_0001,
	(cst_val *)&v_av_in_pr_0002,
	(cst_val *)&v_av_in_pr_0003,
	(cst_val *)&v_av_in_pr_0004,
	(cst_val *)&v_av_in_pr_0005,
	(cst_val *)&v_av_in_pr_0006,
	(cst_val *)&v_av_in_pr_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0001,"v_av_in_i");
DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0002,"avevo");
DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0003,"avevi");
DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0004,"aveva");
DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0005,"avevamo");
DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0006,"avevate");
DEF_STATIC_CONST_VAL_STRING(v_av_in_i_0007,"avevano");

static const cst_val * const gpos_v_av_in_i_list[] = {
	(cst_val *)&v_av_in_i_0001,
	(cst_val *)&v_av_in_i_0002,
	(cst_val *)&v_av_in_i_0003,
	(cst_val *)&v_av_in_i_0004,
	(cst_val *)&v_av_in_i_0005,
	(cst_val *)&v_av_in_i_0006,
	(cst_val *)&v_av_in_i_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0001,"v_av_in_f");
DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0002,"avrò");
DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0003,"avrai");
DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0004,"avrà");
DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0005,"avremo");
DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0006,"avrete");
DEF_STATIC_CONST_VAL_STRING(v_av_in_f_0007,"avranno");

static const cst_val * const gpos_v_av_in_f_list[] = {
	(cst_val *)&v_av_in_f_0001,
	(cst_val *)&v_av_in_f_0002,
	(cst_val *)&v_av_in_f_0003,
	(cst_val *)&v_av_in_f_0004,
	(cst_val *)&v_av_in_f_0005,
	(cst_val *)&v_av_in_f_0006,
	(cst_val *)&v_av_in_f_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_co_p_0001,"v_av_co_p");
DEF_STATIC_CONST_VAL_STRING(v_av_co_p_0002,"abbia");
DEF_STATIC_CONST_VAL_STRING(v_av_co_p_0003,"abbiamo");
DEF_STATIC_CONST_VAL_STRING(v_av_co_p_0004,"abbiate");
DEF_STATIC_CONST_VAL_STRING(v_av_co_p_0005,"abbiano");

static const cst_val * const gpos_v_av_co_p_list[] = {
	(cst_val *)&v_av_co_p_0001,
	(cst_val *)&v_av_co_p_0002,
	(cst_val *)&v_av_co_p_0003,
	(cst_val *)&v_av_co_p_0004,
	(cst_val *)&v_av_co_p_0005,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_co_i_0001,"v_av_co_i");
DEF_STATIC_CONST_VAL_STRING(v_av_co_i_0002,"avessi");
DEF_STATIC_CONST_VAL_STRING(v_av_co_i_0003,"avesse");
DEF_STATIC_CONST_VAL_STRING(v_av_co_i_0004,"avessimo");
DEF_STATIC_CONST_VAL_STRING(v_av_co_i_0005,"aveste");
DEF_STATIC_CONST_VAL_STRING(v_av_co_i_0006,"avessero");

static const cst_val * const gpos_v_av_co_i_list[] = {
	(cst_val *)&v_av_co_i_0001,
	(cst_val *)&v_av_co_i_0002,
	(cst_val *)&v_av_co_i_0003,
	(cst_val *)&v_av_co_i_0004,
	(cst_val *)&v_av_co_i_0005,
	(cst_val *)&v_av_co_i_0006,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0001,"v_av_cd_p");
DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0002,"avrei");
DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0003,"avresti");
DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0004,"avrebbe");
DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0005,"avremmo");
DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0006,"avreste");
DEF_STATIC_CONST_VAL_STRING(v_av_cd_p_0007,"avrebbero");

static const cst_val * const gpos_v_av_cd_p_list[] = {
	(cst_val *)&v_av_cd_p_0001,
	(cst_val *)&v_av_cd_p_0002,
	(cst_val *)&v_av_cd_p_0003,
	(cst_val *)&v_av_cd_p_0004,
	(cst_val *)&v_av_cd_p_0005,
	(cst_val *)&v_av_cd_p_0006,
	(cst_val *)&v_av_cd_p_0007,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_im_p_0001,"v_av_im_p");
DEF_STATIC_CONST_VAL_STRING(v_av_im_p_0002,"abbi");
DEF_STATIC_CONST_VAL_STRING(v_av_im_p_0003,"abbia");
DEF_STATIC_CONST_VAL_STRING(v_av_im_p_0004,"abbiamo");
DEF_STATIC_CONST_VAL_STRING(v_av_im_p_0005,"abbiate");
DEF_STATIC_CONST_VAL_STRING(v_av_im_p_0006,"abbiano");

static const cst_val * const gpos_v_av_im_p_list[] = {
	(cst_val *)&v_av_im_p_0001,
	(cst_val *)&v_av_im_p_0002,
	(cst_val *)&v_av_im_p_0003,
	(cst_val *)&v_av_im_p_0004,
	(cst_val *)&v_av_im_p_0005,
	(cst_val *)&v_av_im_p_0006,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_av_ge_p_0001,"v_av_ge_p");
DEF_STATIC_CONST_VAL_STRING(v_av_ge_p_0002,"avendo");

static const cst_val * const gpos_v_av_ge_p_list[] = {
	(cst_val *)&v_av_ge_p_0001,
	(cst_val *)&v_av_ge_p_0002,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0001,"v_dpv_in_p");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0002,"devo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0003,"debbo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0004,"posso");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0005,"voglio");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0006,"devi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0007,"puoi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0008,"vuoi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0009,"deve");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0010,"può");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0011,"vuole");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0012,"dobbiamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0013,"possiamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0014,"vogliamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0015,"dovete");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0016,"potete");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0017,"volete");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0018,"devono");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0019,"debbono");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0020,"possono");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_p_0021,"vogliono");

static const cst_val * const gpos_v_dpv_in_p_list[] = {
	(cst_val *)&v_dpv_in_p_0001,
	(cst_val *)&v_dpv_in_p_0002,
	(cst_val *)&v_dpv_in_p_0003,
	(cst_val *)&v_dpv_in_p_0004,
	(cst_val *)&v_dpv_in_p_0005,
	(cst_val *)&v_dpv_in_p_0006,
	(cst_val *)&v_dpv_in_p_0007,
	(cst_val *)&v_dpv_in_p_0008,
	(cst_val *)&v_dpv_in_p_0009,
	(cst_val *)&v_dpv_in_p_0010,
	(cst_val *)&v_dpv_in_p_0011,
	(cst_val *)&v_dpv_in_p_0012,
	(cst_val *)&v_dpv_in_p_0013,
	(cst_val *)&v_dpv_in_p_0014,
	(cst_val *)&v_dpv_in_p_0015,
	(cst_val *)&v_dpv_in_p_0016,
	(cst_val *)&v_dpv_in_p_0017,
	(cst_val *)&v_dpv_in_p_0018,
	(cst_val *)&v_dpv_in_p_0019,
	(cst_val *)&v_dpv_in_p_0020,
	(cst_val *)&v_dpv_in_p_0021,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0001,"v_dpv_in_pp");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0002,"dovuto");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0003,"dovuta");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0004,"dovuti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0005,"dovute");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0006,"potuto");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0007,"potuta");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0008,"potuti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0009,"potute");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0010,"voluto");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0011,"voluta");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0012,"voluti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pp_0013,"volute");

static const cst_val * const gpos_v_dpv_in_pp_list[] = {
	(cst_val *)&v_dpv_in_pp_0001,
	(cst_val *)&v_dpv_in_pp_0002,
	(cst_val *)&v_dpv_in_pp_0003,
	(cst_val *)&v_dpv_in_pp_0004,
	(cst_val *)&v_dpv_in_pp_0005,
	(cst_val *)&v_dpv_in_pp_0006,
	(cst_val *)&v_dpv_in_pp_0007,
	(cst_val *)&v_dpv_in_pp_0008,
	(cst_val *)&v_dpv_in_pp_0009,
	(cst_val *)&v_dpv_in_pp_0010,
	(cst_val *)&v_dpv_in_pp_0011,
	(cst_val *)&v_dpv_in_pp_0012,
	(cst_val *)&v_dpv_in_pp_0013,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0001,"v_dpv_in_pr");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0002,"dovei");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0003,"dovetti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0004,"potei");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0005,"volli");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0006,"dovesti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0007,"potesti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0008,"volesti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0009,"dovè");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0010,"dovette");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0011,"potè");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0012,"volle");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0013,"dovemmo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0014,"potemmo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0015,"volemmo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0016,"doveste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0017,"poteste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0018,"voleste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0019,"doverono");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0020,"dovettero");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0021,"potettero");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0022,"poterono");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_pr_0023,"vollero");

static const cst_val * const gpos_v_dpv_in_pr_list[] = {
	(cst_val *)&v_dpv_in_pr_0001,
	(cst_val *)&v_dpv_in_pr_0002,
	(cst_val *)&v_dpv_in_pr_0003,
	(cst_val *)&v_dpv_in_pr_0004,
	(cst_val *)&v_dpv_in_pr_0005,
	(cst_val *)&v_dpv_in_pr_0006,
	(cst_val *)&v_dpv_in_pr_0007,
	(cst_val *)&v_dpv_in_pr_0008,
	(cst_val *)&v_dpv_in_pr_0009,
	(cst_val *)&v_dpv_in_pr_0010,
	(cst_val *)&v_dpv_in_pr_0011,
	(cst_val *)&v_dpv_in_pr_0012,
	(cst_val *)&v_dpv_in_pr_0013,
	(cst_val *)&v_dpv_in_pr_0014,
	(cst_val *)&v_dpv_in_pr_0015,
	(cst_val *)&v_dpv_in_pr_0016,
	(cst_val *)&v_dpv_in_pr_0017,
	(cst_val *)&v_dpv_in_pr_0018,
	(cst_val *)&v_dpv_in_pr_0019,
	(cst_val *)&v_dpv_in_pr_0020,
	(cst_val *)&v_dpv_in_pr_0021,
	(cst_val *)&v_dpv_in_pr_0022,
	(cst_val *)&v_dpv_in_pr_0023,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0001,"v_dpv_in_im");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0002,"dovevo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0003,"potevo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0004,"volevo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0005,"dovevi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0006,"potevi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0007,"volevi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0008,"doveva");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0009,"poteva");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0010,"voleva");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0011,"dovevamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0012,"potevamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0013,"volevamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0014,"dovevate");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0015,"potevate");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0016,"volevate");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0017,"dovevano");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0018,"potevano");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_im_0019,"volevano");

static const cst_val * const gpos_v_dpv_in_im_list[] = {
	(cst_val *)&v_dpv_in_im_0001,
	(cst_val *)&v_dpv_in_im_0002,
	(cst_val *)&v_dpv_in_im_0003,
	(cst_val *)&v_dpv_in_im_0004,
	(cst_val *)&v_dpv_in_im_0005,
	(cst_val *)&v_dpv_in_im_0006,
	(cst_val *)&v_dpv_in_im_0007,
	(cst_val *)&v_dpv_in_im_0008,
	(cst_val *)&v_dpv_in_im_0009,
	(cst_val *)&v_dpv_in_im_0010,
	(cst_val *)&v_dpv_in_im_0011,
	(cst_val *)&v_dpv_in_im_0012,
	(cst_val *)&v_dpv_in_im_0013,
	(cst_val *)&v_dpv_in_im_0014,
	(cst_val *)&v_dpv_in_im_0015,
	(cst_val *)&v_dpv_in_im_0016,
	(cst_val *)&v_dpv_in_im_0017,
	(cst_val *)&v_dpv_in_im_0018,
	(cst_val *)&v_dpv_in_im_0019,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0001,"v_dpv_in_f");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0002,"dovrò");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0003,"potrò");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0004,"vorrò");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0005,"dovrai");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0006,"potrai");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0007,"vorrai");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0008,"dovrà");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0009,"potrà");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0010,"vorrà");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0011,"dovremo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0012,"potremo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0013,"vorremo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0014,"dovrete");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0015,"potrete");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0016,"vorrete");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0017,"dovranno");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0018,"potranno");
DEF_STATIC_CONST_VAL_STRING(v_dpv_in_f_0019,"vorranno");

static const cst_val * const gpos_v_dpv_in_f_list[] = {
	(cst_val *)&v_dpv_in_f_0001,
	(cst_val *)&v_dpv_in_f_0002,
	(cst_val *)&v_dpv_in_f_0003,
	(cst_val *)&v_dpv_in_f_0004,
	(cst_val *)&v_dpv_in_f_0005,
	(cst_val *)&v_dpv_in_f_0006,
	(cst_val *)&v_dpv_in_f_0007,
	(cst_val *)&v_dpv_in_f_0008,
	(cst_val *)&v_dpv_in_f_0009,
	(cst_val *)&v_dpv_in_f_0010,
	(cst_val *)&v_dpv_in_f_0011,
	(cst_val *)&v_dpv_in_f_0012,
	(cst_val *)&v_dpv_in_f_0013,
	(cst_val *)&v_dpv_in_f_0014,
	(cst_val *)&v_dpv_in_f_0015,
	(cst_val *)&v_dpv_in_f_0016,
	(cst_val *)&v_dpv_in_f_0017,
	(cst_val *)&v_dpv_in_f_0018,
	(cst_val *)&v_dpv_in_f_0019,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0001,"v_dpv_co_p");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0002,"debba");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0003,"deva");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0004,"possa");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0005,"voglia");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0006,"dobbiamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0007,"possiamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0008,"vogliamo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0009,"dobbiate");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0010,"possiate");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0011,"vogliate");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0012,"debbano");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0013,"possano");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_p_0014,"vogliano");

static const cst_val * const gpos_v_dpv_co_p_list[] = {
	(cst_val *)&v_dpv_co_p_0001,
	(cst_val *)&v_dpv_co_p_0002,
	(cst_val *)&v_dpv_co_p_0003,
	(cst_val *)&v_dpv_co_p_0004,
	(cst_val *)&v_dpv_co_p_0005,
	(cst_val *)&v_dpv_co_p_0006,
	(cst_val *)&v_dpv_co_p_0007,
	(cst_val *)&v_dpv_co_p_0008,
	(cst_val *)&v_dpv_co_p_0009,
	(cst_val *)&v_dpv_co_p_0010,
	(cst_val *)&v_dpv_co_p_0011,
	(cst_val *)&v_dpv_co_p_0012,
	(cst_val *)&v_dpv_co_p_0013,
	(cst_val *)&v_dpv_co_p_0014,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0001,"v_dpv_co_i");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0002,"dovessi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0003,"potessi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0004,"volessi");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0005,"dovesse");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0006,"potesse");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0007,"volesse");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0008,"dovessimo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0009,"potessimo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0010,"volessimo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0011,"doveste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0012,"poteste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0013,"voleste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0014,"dovessero");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0015,"potessero");
DEF_STATIC_CONST_VAL_STRING(v_dpv_co_i_0016,"volessero");

static const cst_val * const gpos_v_dpv_co_i_list[] = {
	(cst_val *)&v_dpv_co_i_0001,
	(cst_val *)&v_dpv_co_i_0002,
	(cst_val *)&v_dpv_co_i_0003,
	(cst_val *)&v_dpv_co_i_0004,
	(cst_val *)&v_dpv_co_i_0005,
	(cst_val *)&v_dpv_co_i_0006,
	(cst_val *)&v_dpv_co_i_0007,
	(cst_val *)&v_dpv_co_i_0008,
	(cst_val *)&v_dpv_co_i_0009,
	(cst_val *)&v_dpv_co_i_0010,
	(cst_val *)&v_dpv_co_i_0011,
	(cst_val *)&v_dpv_co_i_0012,
	(cst_val *)&v_dpv_co_i_0013,
	(cst_val *)&v_dpv_co_i_0014,
	(cst_val *)&v_dpv_co_i_0015,
	(cst_val *)&v_dpv_co_i_0016,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0001,"v_dpv_cd_p");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0002,"dovrei");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0003,"potrei");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0004,"vorrei");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0005,"dovresti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0006,"potresti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0007,"vorresti");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0008,"dovrebbe");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0009,"potrebbe");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0010,"vorrebbe");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0011,"dovremmo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0012,"potremmo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0013,"voremmo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0014,"dovreste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0015,"potreste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0016,"vorreste");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0017,"dovrebbero");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0018,"potrebbero");
DEF_STATIC_CONST_VAL_STRING(v_dpv_cd_p_0019,"vorrebbero");

static const cst_val * const gpos_v_dpv_cd_p_list[] = {
	(cst_val *)&v_dpv_cd_p_0001,
	(cst_val *)&v_dpv_cd_p_0002,
	(cst_val *)&v_dpv_cd_p_0003,
	(cst_val *)&v_dpv_cd_p_0004,
	(cst_val *)&v_dpv_cd_p_0005,
	(cst_val *)&v_dpv_cd_p_0006,
	(cst_val *)&v_dpv_cd_p_0007,
	(cst_val *)&v_dpv_cd_p_0008,
	(cst_val *)&v_dpv_cd_p_0009,
	(cst_val *)&v_dpv_cd_p_0010,
	(cst_val *)&v_dpv_cd_p_0011,
	(cst_val *)&v_dpv_cd_p_0012,
	(cst_val *)&v_dpv_cd_p_0013,
	(cst_val *)&v_dpv_cd_p_0014,
	(cst_val *)&v_dpv_cd_p_0015,
	(cst_val *)&v_dpv_cd_p_0016,
	(cst_val *)&v_dpv_cd_p_0017,
	(cst_val *)&v_dpv_cd_p_0018,
	(cst_val *)&v_dpv_cd_p_0019,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_im_p_0001,"v_dpv_im_p");
DEF_STATIC_CONST_VAL_STRING(v_dpv_im_p_0002,"voglia");
DEF_STATIC_CONST_VAL_STRING(v_dpv_im_p_0003,"vogli");
DEF_STATIC_CONST_VAL_STRING(v_dpv_im_p_0004,"vogliate");

static const cst_val * const gpos_v_dpv_im_p_list[] = {
	(cst_val *)&v_dpv_im_p_0001,
	(cst_val *)&v_dpv_im_p_0002,
	(cst_val *)&v_dpv_im_p_0003,
	(cst_val *)&v_dpv_im_p_0004,
	0 };


DEF_STATIC_CONST_VAL_STRING(v_dpv_ge_p_0001,"v_dpv_ge_p");
DEF_STATIC_CONST_VAL_STRING(v_dpv_ge_p_0002,"dovendo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_ge_p_0003,"potendo");
DEF_STATIC_CONST_VAL_STRING(v_dpv_ge_p_0004,"volendo");

static const cst_val * const gpos_v_dpv_ge_p_list[] = {
	(cst_val *)&v_dpv_ge_p_0001,
	(cst_val *)&v_dpv_ge_p_0002,
	(cst_val *)&v_dpv_ge_p_0003,
	(cst_val *)&v_dpv_ge_p_0004,
	0 };



DEF_STATIC_CONST_VAL_STRING(gpos_punc,"punc");
DEF_STATIC_CONST_VAL_STRING(gpos_dot,".");
DEF_STATIC_CONST_VAL_STRING(gpos_comma,",");
DEF_STATIC_CONST_VAL_STRING(gpos_colon,":");
DEF_STATIC_CONST_VAL_STRING(gpos_semicolon,";");
DEF_STATIC_CONST_VAL_STRING(gpos_dquote,"\"");
DEF_STATIC_CONST_VAL_STRING(gpos_squote,"'");
DEF_STATIC_CONST_VAL_STRING(gpos_leftparen,"(");
DEF_STATIC_CONST_VAL_STRING(gpos_qmark,"?");
DEF_STATIC_CONST_VAL_STRING(gpos_rightparen,")");
DEF_STATIC_CONST_VAL_STRING(gpos_emark,"!");

static const cst_val * const gpos_punc_list[] = {
    (cst_val *)&gpos_punc,
    (cst_val *)&gpos_dot,
    (cst_val *)&gpos_comma,
    (cst_val *)&gpos_colon,
    (cst_val *)&gpos_semicolon,
    (cst_val *)&gpos_dquote,
    (cst_val *)&gpos_squote,
    (cst_val *)&gpos_leftparen,
    (cst_val *)&gpos_qmark,
    (cst_val *)&gpos_rightparen,
    (cst_val *)&gpos_emark,
    0 };
   

const cst_val * const * const it_gpos[] = {
	gpos_art_def_list,
	gpos_art_indef_list,
	gpos_pre_pro_list,
	gpos_pre_con_list,
	gpos_pre_imp_list,
	gpos_pre_pp_list,
	gpos_dadj_pos_list,
	gpos_dadj_dem_list,
	gpos_dadj_int_list,
	gpos_dadj_ind_list,
	gpos_dadj_num_list,
	gpos_prono_per_list,
	gpos_prono_dem_list,
	gpos_prono_int_list,
	gpos_prono_rel_list,
	gpos_prono_mix_list,
	gpos_prono_ind_list,
	gpos_conjcoo_cop_list,
	gpos_conjcoo_dis_list,
	gpos_conjcoo_adv_list,
	gpos_conjcoo_dec_list,
	gpos_conjcoo_con_list,
	gpos_conjcoo_adj_list,
	gpos_conjcoo_corr_list,
	gpos_sub_dec_list,
	gpos_sub_temp_list,
	gpos_sub_caus_list,
	gpos_sub_fin_list,
	gpos_sub_cond_list,
	gpos_sub_conc_list,
	gpos_sub_cons_list,
	gpos_sub_comp_list,
	gpos_sub_mod_list,
	gpos_sub_exc_list,
	gpos_adv_quan_list,
	gpos_adv_pla_list,
	gpos_adv_time_list,
	gpos_adv_aff_list,
	gpos_adv_neg_list,
	gpos_adv_pro_list,
	gpos_adv_agg_list,
	gpos_v_es_in_p_list,
	gpos_v_es_in_pp_list,
	gpos_v_es_in_pr_list,
	gpos_v_es_in_i_list,
	gpos_v_es_in_f_list,
	gpos_v_es_co_p_list,
	gpos_v_es_co_i_list,
	gpos_v_es_cd_p_list,
	gpos_v_es_im_p_list,
	gpos_v_es_ge_p_list,
	gpos_v_av_in_p_list,
	gpos_v_av_in_pp_list,
	gpos_v_av_in_pr_list,
	gpos_v_av_in_i_list,
	gpos_v_av_in_f_list,
	gpos_v_av_co_p_list,
	gpos_v_av_co_i_list,
	gpos_v_av_cd_p_list,
	gpos_v_av_im_p_list,
	gpos_v_av_ge_p_list,
	gpos_v_dpv_in_p_list,
	gpos_v_dpv_in_pp_list,
	gpos_v_dpv_in_pr_list,
	gpos_v_dpv_in_im_list,
	gpos_v_dpv_in_f_list,
	gpos_v_dpv_co_p_list,
	gpos_v_dpv_co_i_list,
	gpos_v_dpv_cd_p_list,
	gpos_v_dpv_im_p_list,
	gpos_v_dpv_ge_p_list,
	gpos_punc_list,
	0 };

