/*******************************************************/
/**  Autogenerated cart tree for it_int_accent    */
/**  from cart_in_out    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"content");
DEF_STATIC_CONST_VAL_STRING(val_0001,"1");
DEF_STATIC_CONST_VAL_STRING(val_0002,"Accented");
#define CTNODE_it_int_accent_NO_0001 3
DEF_STATIC_CONST_VAL_STRING(val_0003,"NONE");
#define CTNODE_it_int_accent_NO_0000 4
