/*******************************************************/
/**  Autogenerated cart trees for it_int_accent    */
/*******************************************************/

#include "cst_string.h"
#include "cst_cart.h"
#include "cst_regex.h"
#include "it_int_accent_cart.h"


static const cst_cart_node it_int_accent_cart_nodes[] = {
{ 0, CST_CART_OP_IS, CTNODE_it_int_accent_NO_0000, (cst_val *)&val_0000},
{ 1, CST_CART_OP_IS, CTNODE_it_int_accent_NO_0001, (cst_val *)&val_0001},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0002 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 255, CST_CART_OP_NONE, 0, 0}};



static const char * const it_int_accent_feat_table[] = {
"R:SylStructure.parent.gpos",
"stress",
NULL };

const cst_cart it_int_accent_cart = {
  it_int_accent_cart_nodes,
  it_int_accent_feat_table
};
