/*******************************************************/
/**  Autogenerated cart trees for it_int_accent_ds    */
/*******************************************************/

#include "cst_string.h"
#include "cst_cart.h"
#include "cst_regex.h"
#include "it_int_accent_ds_cart.h"


static const cst_cart_node it_int_accent_ds_cart_nodes[] = {
{ 0, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0000, (cst_val *)&val_0000},
{ 1, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0001, (cst_val *)&val_0000},
{ 2, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0002, (cst_val *)&val_0001},
{ 3, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0003, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0004 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0005 },
{ 2, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0007, (cst_val *)&val_0001},
{ 4, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0008, (cst_val *)&val_0006},
{ 3, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0009, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0004 },
{ 4, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0012, (cst_val *)&val_0007},
{ 3, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0013, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0004 },
{ 3, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0016, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0008 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0009 },
{ 4, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0019, (cst_val *)&val_0006},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0005 },
{ 4, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0021, (cst_val *)&val_0007},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0005 },
{ 5, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0023, (cst_val *)&val_0001},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0005 },
{ 6, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0025, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0005 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0010 },
{ 2, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0028, (cst_val *)&val_0001},
{ 3, CST_CART_OP_IS, CTNODE_it_int_accent_ds_NO_0029, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0008 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0009 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0009 },
{ 255, CST_CART_OP_NONE, 0, 0}};



static const char * const it_int_accent_ds_feat_table[] = {
"pos_in_word",
"R:SylStructure.parent.p.name",
"R:SylStructure.parent.gpos",
"stress",
"R:SylStructure.parent.p.pbreak",
"R:SylStructure.parent.p.gpos",
"R:SylStructure.parent.p.apo",
NULL };

const cst_cart it_int_accent_ds_cart = {
  it_int_accent_ds_cart_nodes,
  it_int_accent_ds_feat_table
};
