/*******************************************************/
/**  Autogenerated cart tree for it_int_accent_ds    */
/**  from cart_in_out    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"0");
DEF_STATIC_CONST_VAL_STRING(val_0001,"content");
DEF_STATIC_CONST_VAL_STRING(val_0002,"1");
DEF_STATIC_CONST_VAL_STRING(val_0003,"Accented_I");
#define CTNODE_it_int_accent_ds_NO_0003 5
DEF_STATIC_CONST_VAL_STRING(val_0004,"Inizio_content");
#define CTNODE_it_int_accent_ds_NO_0002 6
DEF_STATIC_CONST_VAL_STRING(val_0005,"primaFW");
#define CTNODE_it_int_accent_ds_NO_0001 7
DEF_STATIC_CONST_VAL_STRING(val_0006,"B");
#define CTNODE_it_int_accent_ds_NO_0009 11
#define CTNODE_it_int_accent_ds_NO_0008 12
DEF_STATIC_CONST_VAL_STRING(val_0007,"BB");
#define CTNODE_it_int_accent_ds_NO_0013 15
#define CTNODE_it_int_accent_ds_NO_0012 16
DEF_STATIC_CONST_VAL_STRING(val_0008,"Accented");
#define CTNODE_it_int_accent_ds_NO_0016 18
DEF_STATIC_CONST_VAL_STRING(val_0009,"NONE");
#define CTNODE_it_int_accent_ds_NO_0007 19
#define CTNODE_it_int_accent_ds_NO_0019 21
#define CTNODE_it_int_accent_ds_NO_0021 23
#define CTNODE_it_int_accent_ds_NO_0023 25
#define CTNODE_it_int_accent_ds_NO_0025 27
DEF_STATIC_CONST_VAL_STRING(val_0010,"altreFW");
#define CTNODE_it_int_accent_ds_NO_0000 28
#define CTNODE_it_int_accent_ds_NO_0029 31
#define CTNODE_it_int_accent_ds_NO_0028 32
