/*******************************************************/
/**  Autogenerated phoneset trees for it    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset it_phoneset;


static const char * const it_featnames[] = {
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 "acc",
 "gem",
 "semi",
 NULL };

static const char * const it_phonenames[] = {
 "i",
 "e",
 "E",
 "a",
 "o",
 "O",
 "u",
 "i1",
 "e1",
 "E1",
 "a1",
 "o1",
 "O1",
 "u1",
 "j",
 "w",
 "p",
 "t",
 "k",
 "b",
 "d",
 "g",
 "f",
 "s",
 "S",
 "v",
 "z",
 "Z",
 "ts",
 "tS",
 "dz",
 "dZ",
 "m",
 "n",
 "J",
 "ng",
 "nf",
 "l",
 "L",
 "r",
 "#",
 NULL };

static const int it_fv_000[] = { 0, 1, 2, 2, 3, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_001[] = { 0, 1, 5, 2, 3, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_002[] = { 0, 1, 5, 2, 3, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_003[] = { 0, 1, 6, 5, 3, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_004[] = { 0, 1, 5, 6, 0, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_005[] = { 0, 1, 5, 6, 0, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_006[] = { 0, 1, 2, 6, 0, 4, 4, 3, 3, 4, 3,   -1 };
static const int it_fv_007[] = { 0, 1, 2, 2, 3, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_008[] = { 0, 7, 5, 2, 3, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_009[] = { 0, 7, 5, 2, 3, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_010[] = { 0, 7, 6, 5, 3, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_011[] = { 0, 7, 5, 6, 0, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_012[] = { 0, 7, 5, 6, 0, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_013[] = { 0, 7, 2, 6, 0, 4, 4, 3, 0, 4, 3,   -1 };
static const int it_fv_014[] = { 3, 1, 2, 2, 3, 4, 4, 0, 3, 4, 0,   -1 };
static const int it_fv_015[] = { 3, 1, 2, 6, 0, 4, 4, 0, 3, 4, 0,   -1 };
static const int it_fv_016[] = { 3, 4, 3, 3, 3, 1, 7, 3, 4, 0, 3,   -1 };
static const int it_fv_017[] = { 3, 4, 3, 3, 3, 1, 8, 3, 4, 0, 3,   -1 };
static const int it_fv_018[] = { 3, 4, 3, 3, 3, 1, 9, 3, 4, 0, 3,   -1 };
static const int it_fv_019[] = { 3, 4, 3, 3, 3, 1, 7, 0, 4, 0, 3,   -1 };
static const int it_fv_020[] = { 3, 4, 3, 3, 3, 1, 8, 0, 4, 0, 3,   -1 };
static const int it_fv_021[] = { 3, 4, 3, 3, 3, 1, 9, 0, 4, 0, 3,   -1 };
static const int it_fv_022[] = { 3, 4, 3, 3, 3, 10, 11, 3, 4, 0, 3,   -1 };
static const int it_fv_023[] = { 3, 4, 3, 3, 3, 10, 8, 3, 4, 0, 3,   -1 };
static const int it_fv_024[] = { 3, 4, 3, 3, 3, 10, 12, 3, 4, 0, 3,   -1 };
static const int it_fv_025[] = { 3, 4, 3, 3, 3, 10, 11, 0, 4, 0, 3,   -1 };
static const int it_fv_026[] = { 3, 4, 3, 3, 3, 10, 8, 0, 4, 3, 3,   -1 };
static const int it_fv_027[] = { 3, 4, 3, 3, 3, 10, 12, 0, 4, 3, 3,   -1 };
static const int it_fv_028[] = { 3, 4, 3, 3, 3, 8, 8, 3, 4, 0, 3,   -1 };
static const int it_fv_029[] = { 3, 4, 3, 3, 3, 8, 12, 3, 4, 0, 3,   -1 };
static const int it_fv_030[] = { 3, 4, 3, 3, 3, 8, 8, 0, 4, 0, 3,   -1 };
static const int it_fv_031[] = { 3, 4, 3, 3, 3, 8, 12, 0, 4, 0, 3,   -1 };
static const int it_fv_032[] = { 3, 4, 3, 3, 3, 13, 7, 0, 4, 0, 3,   -1 };
static const int it_fv_033[] = { 3, 4, 3, 3, 3, 13, 8, 0, 4, 0, 3,   -1 };
static const int it_fv_034[] = { 3, 4, 3, 3, 3, 13, 12, 0, 4, 0, 3,   -1 };
static const int it_fv_035[] = { 3, 4, 3, 3, 3, 13, 9, 0, 4, 3, 3,   -1 };
static const int it_fv_036[] = { 3, 4, 3, 3, 3, 13, 11, 0, 4, 3, 3,   -1 };
static const int it_fv_037[] = { 3, 4, 3, 3, 3, 7, 8, 0, 4, 0, 3,   -1 };
static const int it_fv_038[] = { 3, 4, 3, 3, 3, 7, 12, 0, 4, 0, 3,   -1 };
static const int it_fv_039[] = { 3, 4, 3, 3, 3, 7, 8, 0, 4, 0, 3,   -1 };
static const int it_fv_040[] = { 3, 4, 3, 3, 3, 4, 4, 3, 4, 4, 3,   -1 };
static const int it_fv_041[] = { 0 };

static const int * const it_fvtable[] = {
  it_fv_000, 
  it_fv_001, 
  it_fv_002, 
  it_fv_003, 
  it_fv_004, 
  it_fv_005, 
  it_fv_006, 
  it_fv_007, 
  it_fv_008, 
  it_fv_009, 
  it_fv_010, 
  it_fv_011, 
  it_fv_012, 
  it_fv_013, 
  it_fv_014, 
  it_fv_015, 
  it_fv_016, 
  it_fv_017, 
  it_fv_018, 
  it_fv_019, 
  it_fv_020, 
  it_fv_021, 
  it_fv_022, 
  it_fv_023, 
  it_fv_024, 
  it_fv_025, 
  it_fv_026, 
  it_fv_027, 
  it_fv_028, 
  it_fv_029, 
  it_fv_030, 
  it_fv_031, 
  it_fv_032, 
  it_fv_033, 
  it_fv_034, 
  it_fv_035, 
  it_fv_036, 
  it_fv_037, 
  it_fv_038, 
  it_fv_039, 
  it_fv_040, 
 it_fv_041 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"+");
DEF_STATIC_CONST_VAL_STRING(featval_1,"s");
DEF_STATIC_CONST_VAL_STRING(featval_2,"1");
DEF_STATIC_CONST_VAL_STRING(featval_3,"-");
DEF_STATIC_CONST_VAL_STRING(featval_4,"0");
DEF_STATIC_CONST_VAL_STRING(featval_5,"2");
DEF_STATIC_CONST_VAL_STRING(featval_6,"3");
DEF_STATIC_CONST_VAL_STRING(featval_7,"l");
DEF_STATIC_CONST_VAL_STRING(featval_8,"a");
DEF_STATIC_CONST_VAL_STRING(featval_9,"v");
DEF_STATIC_CONST_VAL_STRING(featval_10,"f");
DEF_STATIC_CONST_VAL_STRING(featval_11,"b");
DEF_STATIC_CONST_VAL_STRING(featval_12,"p");
DEF_STATIC_CONST_VAL_STRING(featval_13,"n");

static const cst_val * const it_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 NULL };

const cst_phoneset it_phoneset = {
  "it",
  it_featnames,
  it_featvals,
  it_phonenames,
  "#",
  41,
  it_fvtable
};
