/*******************************************************/
/**  Autogenerated cart trees for it_phrasing    */
/*******************************************************/

#include "cst_string.h"
#include "cst_cart.h"
#include "cst_regex.h"
#include "it_phrasing_cart.h"


static const cst_cart_node it_phrasing_cart_nodes[] = {
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0000, (cst_val *)&val_0000},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0002, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0004, (cst_val *)&val_0003},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0006, (cst_val *)&val_0004},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0008, (cst_val *)&val_0005},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0010, (cst_val *)&val_0006},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0012, (cst_val *)&val_0007},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0008 },
{ 0, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0014, (cst_val *)&val_0009},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0010 },
{ 1, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0016, (cst_val *)&val_0006},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0008 },
{ 2, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0018, (cst_val *)&val_0011},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 3, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0020, (cst_val *)&val_0012},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 4, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0022, (cst_val *)&val_0012},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 5, CST_CART_OP_IS, CTNODE_it_phrasing_NO_0024, (cst_val *)&val_0013},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0014 },
{ 255, CST_CART_OP_NONE, 0, 0}};



static const char * const it_phrasing_feat_table[] = {
"Simbolic_word_end_punct",
"n.Simbolic_word_start_prepunctuation",
"R:Token.parent.n.name",
"break",
"R:Token.parent.break",
"n.name",
NULL };

const cst_cart it_phrasing_cart = {
  it_phrasing_cart_nodes,
  it_phrasing_feat_table
};
