/*******************************************************/
/**  Autogenerated cart tree for it_phrasing    */
/**  from cart_in_out    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"A");
DEF_STATIC_CONST_VAL_STRING(val_0001,"BB");
#define CTNODE_it_phrasing_NO_0000 2
DEF_STATIC_CONST_VAL_STRING(val_0002,"D");
#define CTNODE_it_phrasing_NO_0002 4
DEF_STATIC_CONST_VAL_STRING(val_0003,"E");
#define CTNODE_it_phrasing_NO_0004 6
DEF_STATIC_CONST_VAL_STRING(val_0004,"F");
#define CTNODE_it_phrasing_NO_0006 8
DEF_STATIC_CONST_VAL_STRING(val_0005,"G");
#define CTNODE_it_phrasing_NO_0008 10
DEF_STATIC_CONST_VAL_STRING(val_0006,"H");
#define CTNODE_it_phrasing_NO_0010 12
DEF_STATIC_CONST_VAL_STRING(val_0007,"B");
DEF_STATIC_CONST_VAL_STRING(val_0008,"B");
#define CTNODE_it_phrasing_NO_0012 14
DEF_STATIC_CONST_VAL_STRING(val_0009,"C");
DEF_STATIC_CONST_VAL_STRING(val_0010,"mB");
#define CTNODE_it_phrasing_NO_0014 16
#define CTNODE_it_phrasing_NO_0016 18
DEF_STATIC_CONST_VAL_STRING(val_0011,"--");
#define CTNODE_it_phrasing_NO_0018 20
DEF_STATIC_CONST_VAL_STRING(val_0012,"1");
#define CTNODE_it_phrasing_NO_0020 22
#define CTNODE_it_phrasing_NO_0022 24
DEF_STATIC_CONST_VAL_STRING(val_0013,"0");
#define CTNODE_it_phrasing_NO_0024 26
DEF_STATIC_CONST_VAL_STRING(val_0014,"NB");
